### PR TITLE
Flatten directory hierarchy so we can freely organize w Xcode groups

### PR DESCRIPTION
**Pull request by montehurd**
- left all the existing groups in-tact
- removed a couple crufty unused files

### CODE REVIEW

**Comment by bgerstle** [comment]
@montehurd :100: my only request is that you mirror the "Wikipedia" folder structure in the "WikipediaUnitTests" folder: 

- create "WikipediaUnitTests/Code"
- move all the code from "WikipediaUnitTests/" and "WikipediaUnitTests/Utilities" into "WikipediaUnitTests/Code"

:sparkles: otherwise looks great! :sparkles:

**Comment by montehurd** [comment]
@bgerstle will do!

**Comment by montehurd** [comment]
@bgerstle done!

**Comment by bgerstle** [comment]
all looks good to me. any final thoughts @coreyfloyd?

**Comment by coreyfloyd** [comment]
@bgerstle already looked. Seems fine. :+1: 

@montehurd build is failing now. :frowning:

**Comment by bgerstle** [comment]
Looks like it was a fluke, tests passed on my machine after a total reset (`git clean -dffx` plus clean & restart Xcode). Merging!

i'm gonna ship it

**Pull request merged**
