### PR TITLE
Localisation updates from https://translatewiki.net.

### PR DESCRIPTION
**Pull request by niedzielski**

### CODE REVIEW

**Comment by bgerstle** [comment]
:+1: lgtm will merge when Travis re-confirms

**Comment by bgerstle** [comment]
@montehurd did you want to give this another look?

**Comment by bgerstle** [comment]
@niedzielski also, nice work on an 800+ LOC contribution to an iOS project :stuck_out_tongue_winking_eye:

**Comment by bgerstle** [comment]
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

noooo!!

**Comment by montehurd** [comment]
@bgerstle lol

**Comment by montehurd** [comment]
@niedzielski hey just a side-note, but in case you closed/reopened to restart travis, you can also restart it by tapping "details" link, then there's a round restart button near right side of the details page.

**Comment by niedzielski** [comment]
Looks like everyone's builds are hanging on `Touching WikipediaUnitTests.xctest`.

**Comment by niedzielski** [comment]
@montehurd thanks! Travis wanted me to sign in with GitHub so I just did it the old fashioned way :)

**Comment by montehurd** [comment]
@niedzielski so weird!

**Comment by montehurd** [comment]
@niedzielski ah makes sense :)

**Comment by montehurd** [comment]
Maybe related? https://github.com/travis-ci/travis-ci/issues/4906

**Comment by bgerstle** [comment]
@montehurd if you scroll to the bottom of that issue, you'll see i've referenced it in some of the commits I've already applied here to work around simulator timeouts.  I don't believe this is related to simulator timeouts, but I'm not sure what else it could be.

**Comment by montehurd** [comment]
IT PASSED!

**Comment by bgerstle** [comment]
i'm tempted to restart it, just to see...

**Comment by bgerstle** [comment]
> The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

**Comment by montehurd** [comment]
Interesting... it passed but not the first time. Had to restart it once.

**Comment by bgerstle** [comment]
@montehurd IMO that means there's no difference. I tried something similar to your strategy with 9ae19125. Removing pre-build starting of sim might re-introduce simulator timeouts as well.

**Comment by montehurd** [comment]
@bgerstle ya i'm grasping at straws at bit :)

**Comment by bgerstle** [comment]
yeah, unfortunately we're not able to get into a box and run stuff manually, and this particular failure means we can't even get error logs—build is silent and just aborted altogether.  i think the last thing to try it stuff w/ the project & groups to see if something's messed up (e.g. that last commit you mentioned).  i've noticed that creating new files in groups doesn't automatically point to the "Code" folder... not sure if that could be related.

**Comment by montehurd** [comment]
Piping to /dev/null still shows failing test error messages though... not sure why. I think once we get this figured out that would be a bit more useful than the mega console spam dump.

**Comment by montehurd** [comment]
Oh yeah! That last commit I mentioned may have screwed something up...

**Comment by montehurd** [comment]
It's so weird though - same xcodebuild command works fine locally...

**Comment by bgerstle** [comment]
Bash redirects are fun: http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-3.html

`foo > bar` redirects `stdout` to whatever `bar` is, which can either be a regular file or "special" file like `stderr`.  error output still shows up because you're not redirecting `stderr`.

**Comment by bgerstle** [comment]
@montehurd yeah, definitely something specific to travis, or only exposed on travis. our Jenkins box has been OK

**Comment by montehurd** [comment]
@bgerstle I think I'll toss the ball back to you here :)

**Comment by montehurd** [comment]
Hmm...

    Could not find minitest-5.8.2 in any of the sources
    Run `bundle install` to install missing gems.

**Comment by bgerstle** [comment]
hm, that's a new one, probably just a temporary issue w/ RubyGems. happens rarely

**Comment by niedzielski** [comment]
I was under the impression this was happening for other patches. Is this unique to my PR?

**Comment by bgerstle** [comment]
@niedzielski not unique, no. we'll split this out to save you from the noise

**Comment by bgerstle** [comment]
it does seem particularly bad for this one though (other PRs have been less problematic for some reason)

**Comment by bgerstle** [comment]
nuked it down to the localization updates, will merge just those so we can put it behind us

**Pull request merged**
