### PR TITLE
Make the gesture recognizer in WMFTableOfContentsAnimator a let

### PR DESCRIPTION
**Pull request by nambatee**

### CODE REVIEW

**Comment by montehurd** [comment]
Oh, sorry, my comment in chat...

> btw i see another place where we're dealing with an optional gesture recognizer in a deinit - WMFTableOfContentsAnimator - in a similar fashion.

... was just pointing out there was another place we handle these like you did in https://github.com/wikimedia/wikipedia-ios/pull/2095.

Did you notice a crash here in WMFTableOfContentsAnimator?

**Comment by nambatee** [comment]
@montehurd this will ensure that the lazy var isn't instantiated in deinit

**Comment by montehurd** [comment]
Thanks. I think that generally we shouldn't have vars be lazy if we need to touch them in deinit, I was just wondering if this particular case had crashes.

**Comment by montehurd** [comment]
(Not saying we shouldn't merge this if no crashes, just curious.)

**Comment by nambatee** [comment]
didn't notice any crashes here

**Comment by coreyfloyd** [comment]
@nambatee is this ready to go? I see it has been sitting for a bit

**Pull request merged**
