### PR TITLE
Pages not adhering to dark mode

### PR DESCRIPTION
**Pull request by nambatee**
https://phabricator.wikimedia.org/T171799

Before

img_0043
img_0044
img_0045

After

img_0034
img_0035
img_0036
img_0037
img_0038
img_0039
img_0040
img_0041
img_0042

### CODE REVIEW

**Comment by nambatee** [comment]
There are changes to localization files because I branched off develop after recent twn sync. I think we'll be adding those translations to 5.6.1 anyway so it shouldn't matter.

**Comment by montehurd** [comment]
@nambatee 

> There are changes to localization files because I branched off develop after recent twn sync. I think we'll be adding those translations to 5.6.1 anyway so it shouldn't matter.

If you rebase on the `releases/5.6.1` branch I think those TWN commits will disappear.

**Comment by montehurd** [comment]
Just be sure to do `git pull origin releases/5.6.1` before rebasing.

**Comment by nambatee** [comment]
@montehurd Rebasing on the `releases/5.6.1` didn't remove the localization strings (with a previous pull).

**Comment by montehurd** [comment]
Hmm we should only be seeing the commits added by your PR, not my commits. Maybe we can batcave for a few tomorrow and get to the bottom of it?

**Pull request closed without merging**
