### PR TITLE
Fix nearby cell updates

### PR DESCRIPTION
**Pull request by bgerstle**
Phab: [T120018](https://phabricator.wikimedia.org/T120018)

---

See testing notes in Phab task.

### CODE REVIEW

**Comment by coreyfloyd** [comment]
We probably should turn on and off when cells are off screen though and when the home view is off screen as well.

**Comment by bgerstle** [comment]
> We probably should turn on and off when cells are off screen though and when the home view is off screen as well.

Already implemented. The HomeVC stops the location manager. The list view also does this automatically by calling `stopUpdates` on its dynamic data source.

**Comment by bgerstle** [comment]
I don't have time this second to investigate when the `stopUpdates` call was added in the completion block, but we should add some tests to verify nearby update behavior. I'm updating the spec doc now.

**Comment by bgerstle** [comment]
Ah, the intent was probably to make the _list_ "static." I'll see what I can do here.

**Comment by coreyfloyd** [comment]
:+1: 

@montehurd you want to review and merge?

**Pull request merged**
