### PR TITLE
delete unused & legacy app icon sizes and add iPad Pro icon

### PR DESCRIPTION
**Pull request by bgerstle**
iPad Pro icon is both required for app submission _and_ causing builds to fail on Jenkins due to `Images.xcassets` diffs dirtying the repo and causing fastlane to error.

Fancy, light new icons:
image

### CODE REVIEW

**Comment by montehurd** [comment]
@bgerstle are you seeing a bunch of icon warnings?

**Comment by coreyfloyd** [comment]
@bgerstle is this good - or do you need to fix something?

**Comment by bgerstle** [comment]
I'm seeing those on master too, not sure what's going on..

**Comment by bgerstle** [comment]
:-1: forgot about the whole AppIconSource thing.. stand by

**Comment by bgerstle** [comment]
@coreyfloyd @Montehurd should be good now: 
image

**Comment by coreyfloyd** [comment]
:+1:

**Comment by montehurd** [comment]
Hmm am I doing something wrong? Still seeing warnings:

screen shot 2015-12-22 at 2 17 49 pm

**Comment by montehurd** [comment]
Seeing warnings on iOS 9 too...

**Comment by montehurd** [comment]
Did "clean" and Xcode restart too.

**Pull request merged**
