### PR TITLE
Fix for article not showing empty view

### PR DESCRIPTION
**Pull request by coreyfloyd**
Also Boyscout - reattempt fetch when network comes back online

### CODE REVIEW

**Comment by bgerstle** [comment]
verified iPad 3 iOS 8.3 :+1: 

- Launch app
- Enable airplane mode
- Try to navigate to article from Explore
- Article view is pushed, showing proper error view & warning banner :white_check_mark:

**Comment by bgerstle** [comment]
@coreyfloyd minor thing: when fetching article after connection comes back online, there's no progress feedback

**Comment by coreyfloyd** [comment]
@bgerstle looked at it and not sure why that is happening - lets put a pin in it and file a ticket to investigate the issue.

**Comment by montehurd** [comment]
Hmm seeing some funky times... not sure if related:

If I turn off wifi, then tap on an article it looks good, but if I go back and try to scroll the feed weird things happen:

untitled mov

Also noticed if I start the app from a clean install w/o wifi, tap through the welcome screens to the feed, and then enable wifi, and then try to refresh, it's just... stuck:
untitled mov

**Comment by coreyfloyd** [comment]
@montehurd not related - and fixed in another pr #462

**Pull request merged**
