### PR TITLE
Fix bug causing search results to not be selectable

### PR DESCRIPTION
**Pull request by bgerstle**
Phab: [T120911](https://phabricator.wikimedia.org/T120911)

### CODE REVIEW

**Comment by montehurd** [comment]
Seems to have fixed it! (The search lang is still implicitly flipping to the article lang though.)

**Comment by montehurd** [comment]
:+1:

**Comment by bgerstle** [comment]
just when i thought i could celebrate :rage4:

> Merging #316 into master will decrease coverage by -13.45% as of ba96d2a

**Comment by bgerstle** [comment]
I think that comment is a lie [codecov report for this PR](https://codecov.io/github/wikimedia/wikipedia-ios?pr=316) shows 22.58%

**Comment by coreyfloyd** [comment]
:+1:

**Pull request merged**
