### PR TITLE
Fix for unit tests not running locally.

### PR DESCRIPTION
**Pull request by montehurd**
Was seeing "_Test target X encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted_" error message when trying to run unit tests locally.

This fixed it: https://github.com/Carthage/Carthage/issues/1002#issue-122848182

### CODE REVIEW

**Comment by montehurd** [comment]
Hmm... also looks like we're no longer committing the visual test reference images? I had to set _-WMFVisualTestBatchRecordMode_ to **NO** once to generate them. Doesn't not saving these defeats the purpose of the visuals test though? Without tracked persistent reference images we can't see if our changes broke anything because we'll have to re-gen them to run the test, but the test will then just produce the exact image we just re-gen'ed...

**Comment by joewalsh** [comment]
@montehurd we are committing the visual test reference images - you might have been running on a platform that didn't have the images generated. They're there for iOS 10.0 and iOS 9.3 on a 6S

**Comment by joewalsh** [comment]
@montehurd I've been able to run tests locally - were you running tests using the app's scheme or one of the other targets?

**Comment by montehurd** [comment]
@joewalsh Ya I tried iOS 9.3 on a 6S sim but no luck. Same issue with "Wikipedia", "WikipediaRTL" and "Wikipedia Test Language" schemes.

**Comment by montehurd** [comment]
Also tried 6 sim.

**Comment by montehurd** [comment]
@joewalsh But you're right about the reference images - with this PR's config tweak the tests do run for me with iOS 9.3 sim without needing to regenerate them.

**Comment by joewalsh** [comment]
@montehurd do you have carthage installed? if not, could you try installing carthage and then re-running the tests without this tweak

**Comment by joewalsh** [comment]
@montehurd also, if you do have it installed, try upgrading to the latest version

**Comment by montehurd** [comment]
@joewalsh lemme will check... 

Oh also I just pushed another PR with a tiny tweak to one of our visual test macros: https://github.com/wikimedia/wikipedia-ios/pull/1099

**Comment by montehurd** [comment]
@joewalsh Ya looks like it's installed. 
"carthage version" says _0.9.2_

**Comment by joewalsh** [comment]
@montehurd try upgrading to 0.18.1 and re-running the tests on develop. if you installed with homebrew, should just be `brew upgrade carthage`

**Comment by montehurd** [comment]
@joewalsh ya updating brew presently... taking a while

**Comment by montehurd** [comment]
@joewalsh Yup updating Carthage fixed it! Thanks for the help!

**Comment by joewalsh** [comment]
@montehurd no problem. I think this is another strike against Carthage though

**Pull request closed without merging**
