### PR TITLE
Minor visual design addition

### PR DESCRIPTION
**Pull request by nirzar**
Added a border around uiimageview using interface builder

Phab card:
https://phabricator.wikimedia.org/T119243

### CODE REVIEW

**Comment by montehurd** [comment]
@bgerstle ah good point.

**Comment by montehurd** [comment]
@bgerstle hey do you want to maybe push a commit drying up `CHROME_OUTLINE_WIDTH (1.0f / [UIScreen mainScreen].scale)` and any other occurrences of `1.0f / [UIScreen mainScreen].scale`?

**Comment by nirzar** [comment]
@montehurd @bgerstle will it crash on non-retina devices? if the line does not show up on ipad2 which is the only non retina device with iOS 8 available, we should be good. I think this is an enhancement, if it was a feature i would be worried.

**Comment by bgerstle** [comment]
@nirzar no crash, good point that we can circle back and handle edge cases later if needed

**Pull request merged**
