### PR TITLE
Add modal browser

### PR DESCRIPTION
**Pull request by coreyfloyd**
https://phabricator.wikimedia.org/T124802

There was some upfront refactoring to make this cleaner:
1. Removing MWKTitles from the Piwik Tracker API 
We were sending titles to Piwik though we weren't really tracking them. This complicated some APIs by requiring extra parameters in some methods.
2. Remove MWKHistoryDiscoveryMethod
This was only being used for restoring scroll position - so it really wasn't needed anymore. This had a similar affect of complicating APIs
3. Rename WMFArticleContainerViewController -> WMFArticleViewController. 
This was an artifact of the old architecture and will be misleading in the new browser architecture.

The real work is WMFArticleBrowserViewController. The browser VC now controls the navigation bar and tool bar for articles. It also maintains the stack for the back forward navigation of the new design.

### CODE REVIEW

**Comment by montehurd** [comment]
Looks way cool! Couple small notes for first testing pass:
- getting assert on link tap 
- white screen on gallery dismiss
- "W" should be white
- nice if "W" tap scrolled to top of article

**Comment by coreyfloyd** [comment]
@montehurd on the color of the W - FYI - its not white in the mocks…

**Comment by montehurd** [comment]
Oh man, I'm *really* liking how this works!

**Comment by montehurd** [comment]
On issue - if I'm reading an article, then search and select a result, it's pushing *another* chrome VC on the stack rather than pushing the search selection article into the chrome VC from the article we had been reading.

**Comment by montehurd** [comment]
Seeing crashes on device when trying 3d peek on article links.

**Comment by montehurd** [comment]
I haven't tested the app icon shortcuts yet - especially the "Continue reading..." one. May want to check that.

**Comment by coreyfloyd** [comment]
@montehurd so I think I am about good on your feedback…

> One issue - if I'm reading an article, then search and select a result, it's pushing another chrome VC on the stack rather than pushing the search selection article into the chrome VC from the article we had been reading.

fixed

> nice if "W" tap scrolled to top of article (out of scope)

yeah out of scope

> since refresh button is gone use pull to refresh? (out of scope?)

ditto - that is in a separate ticket somewhere

> Seeing crashes on device when trying 3d peek on article links.

On master - not this patch

> getting assert on link tap

fixed

> white screen on gallery dismiss

fixed


I'm working sole on the tweak now - let me know if you are good otherwise.

**Comment by montehurd** [comment]
One tiny layout issue. On my device, when I'm reading an article and scroll, I'm seeing the article show through a 1 or 2 pixel horizontal line *beneath* the bottom toolbar. Do you see this too?

**Comment by montehurd** [comment]
Oh and I just tested app icon "Continue reading" 3d touch shortcut. Is broken - took me directly to feed instead of article.

**Comment by coreyfloyd** [comment]
@montehurd 

> Oh and I just tested app icon "Continue reading" 3d touch shortcut. Is broken - took me directly to feed instead of article.

Fixed

> One tiny layout issue. On my device, when I'm reading an article and scroll, I'm seeing the article show through a 1 or 2 pixel horizontal line beneath the bottom toolbar. Do you see this too?

Can't reproduce

**Comment by montehurd** [comment]
Found a bug related to the `Fix article presentation from search` issue - the same things still happens if you select an item from the "Read more" items at the bottom of the article.

**Comment by montehurd** [comment]
Oh it's also happening if you select an article from the "Similar pages" list from the "About this article" footer menu.

**Comment by montehurd** [comment]
Merging even though we're seeing some test failure so we can get this out for testing. Will double back with Brian on Monday.

**Pull request merged**
