### PR TITLE
Update AboutViewController.plist

### PR DESCRIPTION
**Pull request by josve05a**
Fix link to GitHub repository (from a 404 link)
T127923

### CODE REVIEW

**Comment by montehurd** [comment]
:+1:

**Comment by coreyfloyd** [comment]
:+1:

**Comment by bgerstle** [comment]
:+1: 3! 3 plus ones! bah ha ha ha

**Comment by josve05a** [comment]
@bgerstle 3 times as many thumbs up as characters changed in the commit xD

**Pull request merged**
