### PR TITLE
Fixed `Article storage and syncing` label clips long translation

### PR DESCRIPTION
**Pull request by VictorBX**
https://phabricator.wikimedia.org/T196179

Updated the `EraseSavedArticlesView.xib` to support multiple lines on the title label.
Screen Shot 2019-10-05 at 8 19 09 PM

### CODE REVIEW

**Comment by tonisevener** [comment]
@VictorBX thank you for the fix! Would it be possible to get this fixed in iOS11 too? I notice it's not wrapping.

Screen Shot 2019-10-07 at 11 17 52 AM

**Comment by VictorBX** [comment]
@tonisevener Good catch! I'll tackle that later today.

**Comment by VictorBX** [comment]
@tonisevener @nambatee I pushed the updates last night. Please let me know if you run into any other issues.

**Comment by tonisevener** [comment]
@VictorBX looks good, thank you!

**Pull request merged**
