### PR TITLE
Moving to Swift Package Manager

### PR DESCRIPTION
**Pull request by codebendr-product-designer**
**Phabricator:** 

### Notes
* This `PR` is my attempt to move the project to swift package manager so we can take advantage of Micro App Architecture.
* Am using an M1 16GB RAM and I noticed how long it took for the project to build. 
* The first thing I did was just create a workspace and an empty SPM.
* Am planning on moving all `Models` & `ViewModels` as per Schema to SPM. 
* Project can be opened via **Wikipedia.xcworkspace**

Update Xcode Project with Wikipedia.xcworkspace. 
Screen Shot 2022-02-24 at 12 34 53 PM

Additional Files. 
Screen Shot 2022-02-24 at 12 35 47 PM

### CODE REVIEW

**Comment by tonisevener** [comment]
Hi @codebendr-product-designer, thanks for the PR! It's a cool idea and it would be great to reduce our compile times. I need to discuss this further with the engineering team before considering this - we'll let you know our thoughts next week. If you could provide any more information on the ultimate end state you had in mind (blog posts, sample project repos, other modules besides models that you plan on), that would be helpful for our discussions.

**Comment by codebendr-product-designer** [comment]
> Hi @codebendr-product-designer, thanks for the PR! It's a cool idea and it would be great to reduce our compile times. I need to discuss this further with the engineering team before considering this - we'll let you know our thoughts next week. If you could provide any more information on the ultimate end state you had in mind (blog posts, sample project repos, other modules besides models that you plan on), that would be helpful for our discussions.

Hi @tonisevener thanks for your comment. Sounds good discussing this with the team before I break the whole codebase. 
Am currently reviewing your existing schemas and dependencies in the codebase to to understand how everything is wired together.  

**End States**
1. Blogs Posts, Models, Network Layer etc. will be in separate modules or libraries that can be imported as dependencies 
2. UI including storyboard resources will be kept in the same Library as a design system and targets will be created as target 
3. For Sample Project Repos we will keep them as targets as you currently have it.
4. Business logic will be kept as Modules under one library  
5. Basically everything as a vertical slice with business logic as horizontal. 
6. UI & Unit test will be will be kept in different libraries. We have to consider how these tests will be integrated for GitHub actions. But the idea is to run tests in complete isolation. Which am sure is already being done. 
7. Of course we have to inverse some of the dependencies and make changes to code to support the separation. 

I hope this helps?🤔
img width="1372" alt="Screen Shot 2022-02-25 at 7 36 28 PM" src="https://user-images.githubusercontent.com/35074528/155783843-a19d7bae-0a94-4d14-87c1-861dd9ad3b94.png">

**Comment by tonisevener** [comment]
@codebendr-product-designer Sorry, my mention of blog posts and sample code repos may have been confusing. I just meant, are there any resources that you would suggest we look at (like blog posts or other project repos) that demonstrate an example of Micro App Architecture? Something to give us an idea of the end-state for this. We don't actually have blog posts as a model or feature in our app 🙂  But yes, everything else you mentioned with the different modules is more clear, thanks.

**Comment by codebendr-product-designer** [comment]
> @codebendr-product-designer Sorry, my mention of blog posts and sample code repos may have been confusing. I just meant, are there any resources that you would suggest we look at (like blog posts or other project repos) that demonstrate an example of Micro App Architecture? Something to give us an idea of the end-state for this. We don't actually have blog posts as a model or feature in our app 🙂 But yes, everything else you mentioned with the different modules is more clear, thanks.

@tonisevener sorry for misunderstanding. yes I have some blog posts and video links
1. [iOS App Architecture in 2022](https://alejandromp.com/blog/ios-app-architecture-in-2022/)

**Comment by tonisevener** [comment]
@codebendr-product-designer awesome, thanks so much!

**Comment by tonisevener** [comment]
Hi @codebendr-product-designer! First off, I want to give a huge thanks for expressing interest in this, the effort you've already put into this and for providing those resources for us to look into. We discussed this as a team and have some thoughts.

Something I want to point out is that we are a small team of 3 iOS engineers. Your resources seem to suggest that this architecture provides more of a benefit to larger teams with feature-specific subteams. This aspect isn't really a problem for us because our dev team is so small. We also have less bandwidth to oversee a major rearchitecting of the app, even if it is just code review. That being said, I do think the modular approach with SPM encourages good decoupling practices and our project structure could definitely use some cleanup and reorganizing. 

We want to take baby steps and slowly move to this end state one simple module at a time. We have an alternative first module in mind to spin off from our WMF Framework: Utilities. The Utilities files are currently located in the WMF Framework > Utilities project group. I started a small Utilities package in the branch `SPM-test` containing the first couple of utilities files (`Array+Chunked.swift and `Array+SafeIndex.swift`), if you want to get an idea of what we're thinking.

I'm going to go ahead and close this PR in favor of an initial PR with one Utilities module containing those files in WMF Framework > Utilities. After this is merged we'll regroup and discuss how it's going and if we want to move onto more modules (an obvious next one is a UI module with the contents of the WMF Framework > UI group). Hope this direction helps. Thanks so much!

**Comment by tonisevener** [comment]
Hi @codebendr-product-designer! First off, I want to give a huge thanks for expressing interest in this, the effort you've already put into this and for providing those resources for us to look into. We discussed this as a team and have some thoughts.

Something I want to point out is that we are a small team of 3 iOS engineers. Your resources seem to suggest that this architecture provides more of a benefit to larger teams with feature-specific subteams. This aspect isn't really a problem for us because our dev team is so small. We also have less bandwidth to oversee a major rearchitecting of the app, even if it is just code review. That being said, I do think the modular approach with SPM encourages good decoupling practices and our project structure could definitely use some cleanup and reorganizing. 

We want to take baby steps and slowly move to this end state one simple module at a time. We have an alternative first module in mind to spin off from our WMF Framework: Utilities. The Utilities files are currently located in the WMF Framework > Utilities project group. I started a small Utilities package in the branch `SPM-test` containing the first couple of utilities files (`Array+Chunked.swift and `Array+SafeIndex.swift`), if you want to get an idea of what we're thinking.

I'm going to go ahead and close this PR in favor of an initial PR with one Utilities module containing those files in WMF Framework > Utilities. After this is merged we'll regroup and discuss how it's going and if we want to move onto more modules (an obvious next one is a UI module with the contents of the WMF Framework > UI group). Hope this direction helps. Thanks so much!

**Comment by codebendr-product-designer** [comment]
@tonisevener Thank you too. its always interesting reviewing open source projects that have millions of users. Anyway just incase you are hiring, let me know. :) I will take a look at SPM-test and contribute where I can. ciao!

**Pull request closed without merging**
