### PR TITLE
Add guards to didMoveToSuperview.

### PR DESCRIPTION
**Pull request by montehurd**

### CODE REVIEW

**Comment by joewalsh** [comment]
what is this fixing?

**Comment by montehurd** [comment]
@joewalsh these seem to fire when the view is removed from the superview too. no need to do the override code in that case - especially where colors/frames are concerned.

**Comment by joewalsh** [comment]
@montehurd none of the one-time setup code should really be in `didMoveToSuperview` - it should be triggered on init for views created in code or in `awakeFromNib` when it relies on other views loaded from a nib

**Comment by montehurd** [comment]
@joewalsh lgtm

**Pull request merged**
