### PR TITLE
ensure assets are available when needed

### PR DESCRIPTION
**Pull request by joewalsh**
- Move assets folder to the WMFModel framework
- Copy assets in the WikipediaAppUtils class initializer
- Ensure clients use the class to get the assets path so that the assets are copied before needed

### CODE REVIEW

**Comment by joewalsh** [comment]
https://phabricator.wikimedia.org/T146315

**Comment by joewalsh** [comment]
@coreyfloyd @montehurd the commit is a "revert revert" because I accidentally committed and pushed to develop (thinking I had created a branch when I hadn't)

**Comment by montehurd** [comment]
I'll test this a bit in the morning.

**Comment by montehurd** [comment]
👍 tested. looks good

**Pull request merged**
