### PR TITLE
integrate travis & codecov

### PR DESCRIPTION
**Pull request by bgerstle**
Let's get tested! :construction_worker:

### CODE REVIEW

**Comment by bgerstle** [comment]
@coreyfloyd i've changed the Travis settings to not build "prs" to prevent ["redundant" statuses](https://github.com/travis-ci/travis-ci/issues/3241)

**Comment by bgerstle** [comment]
so.... beautiful :sob:

**Comment by coreyfloyd** [comment]
Since the pull request is telling me to merge, how can I argue?

:+1:

**Comment by coreyfloyd** [comment]
@montehurd any issues before i merge?

**Comment by bgerstle** [comment]
@coreyfloyd hold off, imma fix some more stuff... and add a codecov badge :sunglasses:

**Comment by coreyfloyd** [comment]
@bgerstle you're my hero

Hero

**Comment by montehurd** [comment]
@coreyfloyd mergeit!

**Comment by bgerstle** [comment]
:checkered_flag:

**Pull request merged**
