### PR TITLE
Localisation updates from https://translatewiki.net.

### PR DESCRIPTION
**Pull request by translatewiki**
Translation updates

### CODE REVIEW

**Comment by tonisevener** [comment]
I dug a bit into this - the import script broke due to some of the nqo plural translations being off. I updated in translatewiki and made a support thread about it - https://translatewiki.net/w/i.php?title=Support&lqt_method=talkpage_new_thread#iOS_plural_syntax_off_for_N'Ko_58369.

**Comment by mcleinman** [comment]
Thank you @tonisevener !

**Comment by tonisevener** [comment]
It made it past the import script - I'm a bit stuck on why the test is failing though.

**Comment by mcleinman** [comment]
@tonisevener Assigning this one to you, since it now includes my commits to add N'Ko to the app (and updated documentation).

**Review by tonisevener — APPROVED** [review]
Looks and tests great! Thanks for figuring this one out.

**Pull request merged**
