### PR TITLE
Revert to using CocoaPods exclusively for dependency management.

### PR DESCRIPTION
**Pull request by bgerstle**
We were having issues with debug symbols (specifically PromiseKit?) crashing the debugger when built from someone else's machine.  While attempting to fix the issue we tried:

1. Switching back to "official" PromiseKit swift-2.0-beta5 branch (off of my fork)
a. Didn't fix the issue
2. Forcing devs to re-compile Carthage dependencies before building
b. Couldn't get it to build in Travis even after working around GitHub API limit, setting for an out of date Carthage via Homebrew, and eventually the last straw: Code Signing issues

As a result, I decided to try having our dependencies integrated via CocoaPods would work locally and on CI.  This seems to work and has the added benefits of:

- Using one dependency manager, simplifying the build process
- Having all dependencies committed to the repo, thus fewer "pre-build" dependencies

### CODE REVIEW

**Comment by bgerstle** [comment]
@montehurd @coreyfloyd please verify that you can [use the console debugger](https://cloud.githubusercontent.com/assets/444217/10311639/95c9c64e-6c15-11e5-901b-18df00481cf0.png) and [visual debugger](https://cloud.githubusercontent.com/assets/444217/10311628/8931df70-6c15-11e5-9d75-f33f59766cbb.png)

**Comment by coreyfloyd** [comment]
:+1:  Works for me me

**Comment by bgerstle** [comment]
having some code signing issues now when archiving.. investigating

**Comment by bgerstle** [comment]
package was submitted successfully to iTunes Connect (although fastlane had some issues verifying due to iTC website changes—will upgrade in a separate PR)

**Pull request merged**
