### PR TITLE
Update explore header styling.

### PR DESCRIPTION
**Pull request by montehurd**
https://phabricator.wikimedia.org/T125460 
(See epic for follow-on updates: https://phabricator.wikimedia.org/T124484 )

**Featured**
screen shot 2016-01-29 at 6 18 55 pm

**Random**
screen shot 2016-01-29 at 6 19 34 pm

**Because you read**
screen shot 2016-01-29 at 6 20 20 pm

**Main page and PoTD** (needs follow-on to style PoTD without text overlay, see epic)
screen shot 2016-01-29 at 6 19 04 pm

**Continue reading** (needs follow-on to use search result type styling so we get icon, see epic)
screen shot 2016-01-29 at 6 41 01 pm

 **Nearby** (needs follow-on to convert lat/long to town, see epic)
screen shot 2016-01-29 at 6 20 05 pm

### CODE REVIEW

**Comment by nirzar** [comment]
@montehurd few important style changes

1. The line below the header needs to go. its important that the header and cards dont have line between.
2. the first title of the header is 12px regular
3. the second title is 14px bold
4. the gray for titles should be wmf_customGray from wmf colors
5.  is it possible to remove the top padding of only the first item just after the header? 

Otherwise this is looking really great :+1:

**Comment by bgerstle** [comment]
:+1: looks nice 🎨

**Comment by montehurd** [comment]
@bgerstle Fixed!

**Comment by montehurd** [comment]
Hmm... Travis not finishing?

**Comment by montehurd** [comment]
Huh guess the queue was backed up for a while. Passed.

**Pull request merged**
