### PR TITLE
Update "In the news" card appearance

### PR DESCRIPTION
**Pull request by joewalsh**
Also updated wikidata description capitalization handling. This can't be done at JSON parsing time on `MWKSearchResult` or `WMFFeedArticlePreview` because neither class is aware of their `siteURL` (which would have the appropriate language to use for capitalization.

### CODE REVIEW

**Comment by montehurd** [comment]
On clean install I had to scroll down to May 13th before I saw `In the news`.

**Comment by montehurd** [comment]
3d touch-peeking on the side-to-side scrolling `In the news` cards is peeking the detail view rather than the article for that news item.

**Comment by montehurd** [comment]
Noticed when you're on the detail view and rotate to landscape we're using multiple columns... just double-checking that's intentional...

screen shot 2017-05-19 at 2 45 22 pm

**Comment by montehurd** [comment]
Saw this crash on iOS 9.3 on iPhone 6s sim:

<pre>
2017-05-19 14:47:58.968 Wikipedia[2635:6221598] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'no UICollectionViewLayoutAttributes instance for -layoutAttributesForSupplementaryElementOfKind: UICollectionElementKindSectionFooter at path <NSIndexPath: 0xc000000000000216> {length = 2, path = 2 - 0}'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001108fcd85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000110370deb objc_exception_throw + 48
	2   CoreFoundation                      0x00000001108fcbea +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x000000010fb5dd5a -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   UIKit                               0x000000010edcecbb -[UICollectionViewData layoutAttributesForSupplementaryElementOfKind:atIndexPath:] + 964
	5   UIKit                               0x000000010edc8f3c __50-[UICollectionViewData validateSupplementaryViews]_block_invoke + 288
	6   CoreFoundation                      0x000000011082e1e6 __65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 102
	7   CoreFoundation                      0x000000011082e0af -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 159
	8   UIKit                               0x000000010edc8df6 -[UICollectionViewData validateSupplementaryViews] + 117
	9   UIKit                               0x000000010edca42f -[UICollectionViewData validateLayoutInRect:] + 83
	10  UIKit                               0x000000010ed7753a -[UICollectionView layoutSubviews] + 199
	11  UIKit                               0x000000010e5b2980 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 703
	12  QuartzCore                          0x000000010d346c00 -[CALayer layoutSublayers] + 146
	13  QuartzCore                          0x000000010d33b08e _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
	14  QuartzCore                          0x000000010d33af0c _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	15  QuartzCore                          0x000000010d32f3c9 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 277
	16  QuartzCore                          0x000000010d35d086 _ZN2CA11Transaction6commitEv + 486
	17  QuartzCore                          0x000000010d35d7f8 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 92
	18  CoreFoundation                      0x0000000110821c37 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	19  CoreFoundation                      0x0000000110821ba7 __CFRunLoopDoObservers + 391
	20  CoreFoundation                      0x00000001108177fb __CFRunLoopRun + 1147
	21  CoreFoundation                      0x00000001108170f8 CFRunLoopRunSpecific + 488
	22  GraphicsServices                    0x0000000114342ad2 GSEventRunModal + 161
	23  UIKit                               0x000000010e4f7f09 UIApplicationMain + 171
	24  Wikipedia                           0x000000010c7928d9 main + 105
	25  libdyld.dylib                       0x000000011365892d start + 1
	26  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException

</pre>

**Comment by montehurd** [comment]
On clean install using `WikipediaRTL` scheme I'm seeing just a single `In the news` card for for Friday May 19...

screen shot 2017-05-19 at 2 54 15 pm

... I double-checked to see if there actually were more items by looking at develop, and it appears there are...

screen shot 2017-05-19 at 2 56 45 pm

**Comment by montehurd** [comment]
Missing capitalization here...
screen shot 2017-05-19 at 3 05 28 pm

**Comment by montehurd** [comment]
Overall looks great!!! The small issues noted above were the only bits I noticed which could maybe use some tweaks.

**Comment by joewalsh** [comment]
1. Multi-column is intentional until Carolyn specifies a design for that case
2. Let me know if you have repro steps for the crash
3. May 19th - one card per day (with one story) is expected behavior based on the design
4. Will fix capitalization

**Comment by montehurd** [comment]
> May 19th - one card per day (with one story) is expected behavior based on the design

Hmm in the second screenshot I posted in that comment it looks like there was more than one story...

**Comment by joewalsh** [comment]
@montehurd yeah - it will only show one story, even if there are multiple

**Comment by montehurd** [comment]
@joewalsh ah sorry josh helped clear this up! my bad!

**Comment by montehurd** [comment]
I tried repro on iOS 9.3 crash but so far no luck...

I did notice one detail view issue on clean install on iOS 9.3 vs iOS 10.3:

On iOS 10.3 I see date headers:
screen shot 2017-05-22 at 12 13 34 pm

But on iOS 9.3 they seem to be gone:
screen shot 2017-05-22 at 12 12 03 pm

**Comment by joewalsh** [comment]
@montehurd are you sure it was a clean install of 9.3? That issue is expected on a news section loaded with an older version of the app. I was unable to repro the missing header issue on a clean install of 9.3.

screen shot 2017-05-22 at 3 26 10 pm

**Comment by montehurd** [comment]
Ah lemme re-try...

**Comment by montehurd** [comment]
Huh I'd swear it was clean install (I seem to recall going through the welcome screens) but now I can't repro...

**Pull request merged**
