### PR TITLE
Try to fix CI flakes

### PR DESCRIPTION
**Pull request by bgerstle**
We all love :snowflake:, but not these kinds of flakes :rage4:.

- Use xctest for everything, and change output to be more informative (sorry, RSpec-style is cool, but dots don't say much)
- Add workaround for XCTest not liking expectations fulfilled after their wait contexts in our PromiseKit categories for XCTest
- bring back `WMFSearchFetcherTests`, but w/ longer timeouts :hourglass: 
- coup de grace: `before_script` workarounds from https://github.com/travis-ci/travis-ci/issues/2829

### CODE REVIEW

**Comment by coreyfloyd** [comment]
:+1:

**Comment by montehurd** [comment]
"NONE SHALL PASS!" - Travis

**Comment by bgerstle** [comment]
Finally found out why `WMFSearchFetcherTests` are causing issues:

> 2015-11-21 14:18:08.473 Wikipedia Debug[28578:11207913] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'API violation - creating expectations while already in waiting mode.'

First time I've ever seen it, but could explain why tests suddenly fail and wreak havoc in CI.  Fixing now...

**Comment by bgerstle** [comment]
@coreyfloyd @montehurd that's 3 in a row now. let's hope the trend continues 😁

**Pull request merged**
