### PR TITLE
today section block

### PR DESCRIPTION
**Pull request by coreyfloyd**
https://phabricator.wikimedia.org/T127859

This includes:
- Sort update ordering for the "today" sections
- Multi POtD
- Multi Nearby
- Archive logic updates

### CODE REVIEW

**Comment by bgerstle** [comment]
@coreyfloyd `WMFExploreSectionSchemaTests` are broken, as i'd expect since you changed the order. can you fix 'em up?

**Comment by bgerstle** [comment]
:+1: but i have a suggestion: "More nearby your location" doesn't make sense now that we have multiple sections, which may or may not point to your current location. IMO it should mention the placemark, e.g. "More nearby Delray Beach"

**Comment by montehurd** [comment]
@bgerstle gonna defer to your judgement on this one.

**Comment by coreyfloyd** [comment]
@bgerstle should be good

**Comment by bgerstle** [comment]
@coreyfloyd tests pass for me locally. i'll let you merge since i pushed latest changes :+1:

**Pull request merged**
