### PR TITLE
[T172565] Ignore smart invert colors where appropriate

### PR DESCRIPTION
**Pull request by joewalsh**
Native view component of: https://phabricator.wikimedia.org/T172565

Web view changes will be a follow on.

### CODE REVIEW

**Comment by montehurd** [comment]
@joewalsh 

I don't see the changes take effect until I completely shut down the app and restart it. Otherwise looks lgtm. Want to address that as follow-on?

**Comment by montehurd** [comment]
Oh weird... now it is changing w/o restart... not sure what I did the first time...

**Comment by montehurd** [comment]
Ok I have repro steps:
- go to iOS settings and ensure smart invert is off
- put app theme to default
- completely stop app
- go to iOS settings and enable smart invert
- re-start app
- go to settings in app and change appearance theme to dark
- settings is now inverted dark mode (i.e. bright) as is explore

**Comment by joewalsh** [comment]
@montehurd dark theme should be immune to the system setting

**Comment by montehurd** [comment]
Screenshots from repro steps:

screen shot 2017-09-07 at 2 30 23 pm
screen shot 2017-09-07 at 2 30 30 pm

**Comment by montehurd** [comment]
@joewalsh screenshots above

**Comment by joewalsh** [comment]
@montehurd it can be addressed in a follow-on

**Comment by montehurd** [comment]
@joewalsh here's ticket for follow-on https://phabricator.wikimedia.org/T175310

**Pull request merged**
