### PR TITLE
Fix views affected by Swift 5 compiler bug

### PR DESCRIPTION
**Pull request by nambatee**
https://phabricator.wikimedia.org/T221906
https://phabricator.wikimedia.org/T221683
https://phabricator.wikimedia.org/T220694

~~I couldn't reproduce this consistently so this might not be the ultimate fix. It looked like the row height was off - all the rows were 44. It would make sense cause `heightForRowAt` can be called before the cells are available, causing custom cells to have the default height of 44. That was preventing me from changing the theme.~~

~~Let me know if you've seen it behave differently (as in if you were unable to change the theme while the table view looked ok).~~

### CODE REVIEW

**Comment by joewalsh** [comment]
Table view looks fine for me- it doesn't repro on the debug build in the simulator but does repro on the release build

**Comment by joewalsh** [comment]
Ready for review - something changed in Swift 5. On release builds, subclasses of classes that conform to an obj-c protocol and are adding a method that should conform to that protocol but not explicitly overriding a superclass implementation are compiled in such a way that they aren't called. Adding `@objc` fixed the issue. Might not be a complete understanding of what's going on, so happy to hear other info if anyone has it

**Comment by nambatee** [comment]
https://bugs.swift.org/browse/SR-10257

**Comment by nambatee** [comment]
lgtm

**Pull request merged**
