### PR TITLE
Handle denied access to location & disabled location services

### PR DESCRIPTION
**Pull request by bgerstle**
Phab: [T120768](https://phabricator.wikimedia.org/T120768)

---

## Acceptance criteria
- [x] Remove nearby from feed when
  - [x] Our app specifically is denied
  - [x] Location services are globally disabled
- [x] Re-add to feed when our app is given access
- [x] Prompt user for location access when location services are enabled
- [x] Fix issue w/ multiple Nearby error cells being displayed (need to get repro steps, has to do w/ re-gaining location access when we already have results—at least in simulator)

## Regression tests
- [x] Related section additions/updates

### CODE REVIEW

**Comment by bgerstle** [comment]
Not necessary to merge for upcoming beta release, just posting as WIP so I can pick up where I left off afterwards.

**Comment by bgerstle** [comment]
@coreyfloyd @montehurd removed WIP on this, and created subtask for "More nearby" location handling

**Comment by coreyfloyd** [comment]
:+1:

**Comment by bgerstle** [comment]
:-1: there's something going on since lazy feed loading was merged that is causing nearby to only show placeholders after access is re-granted. investigating 🕵

**Comment by bgerstle** [comment]
ok, should work now :+1:

**Pull request merged**
