### PR TITLE
[BUG] Batch edit selection indicator is not centered

### PR DESCRIPTION
**Pull request by nambatee**
https://phabricator.wikimedia.org/T192859

### CODE REVIEW

**Comment by montehurd** [comment]
One thing to check...

On develop we're making room for the notch:
screen shot 2018-04-23 at 4 16 44 pm


On this PR it looks like it's no longer making the notch affordance:
screen shot 2018-04-23 at 4 14 53 pm

**Comment by nambatee** [comment]
@montehurd on develop, it looks like we're making room for the notch but it's only because the indicator is not centered

not_centered

**Comment by montehurd** [comment]
@nambatee 

iirc for the X it needs to be centered with respect to the safe layout margins, so we'd ignore the part to the left of the orange line below:

39457873-d2595642-4cbe-11e8-8529-ba78caf5f0db

...at least that's my reading of the HIG image...
screen shot 2018-04-30 at 6 48 33 pm

**Comment by montehurd** [comment]
Not a big deal though. Would it be ok to just add a design review note for Carolyn to check landscape on X?

**Comment by nambatee** [comment]
added WIP til questions answered https://phabricator.wikimedia.org/T192859#

**Pull request merged**
