### PR TITLE
Don't update search empty VC from results list, let the search VC con…

### PR DESCRIPTION
**Pull request by coreyfloyd**
…trol it.

### CODE REVIEW

**Comment by bgerstle** [comment]
too damn long

**Comment by bgerstle** [comment]
> Merging #428 into master will decrease coverage by -0.14

wat

**Comment by bgerstle** [comment]
:-1: @coreyfloyd there's a bug now in saved:

- Enable NLC (I used 3G)
- Save a page on Explore or "More like" list
- Immediately navigate to "Saved" tab
- Item shows in "Saved" w/ just title
  - Expected: item shows description & image placeholder once metadata is downloaded, eventually downloading image
  - Actual: item shows w/ title & truncated description w/o image:

image

I suspect it's due to the cell needing to be completely reloaded (and laid out by the table view), which doesn't occur when you configure in place

**Comment by bgerstle** [comment]
@coreyfloyd just double checked, this works on master

**Comment by bgerstle** [comment]
:+1: see [testing notes](https://phabricator.wikimedia.org/T124514#1971476) @montehurd any thoughts?

**Comment by montehurd** [comment]
@bgerstle checking...

**Pull request merged**
