### PR TITLE
Fix carthage link in README

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by davidxia** [comment]
@joewalsh @coreyfloyd

**Comment by joewalsh** [comment]
!jenkins test

**Comment by joewalsh** [comment]
Thanks, @davidxia !

**Comment by joewalsh** [comment]
ok to test

**Comment by joewalsh** [comment]
!jenkins test

**Comment by joewalsh** [comment]
!jenkins ok to test

**Comment by davidxia** [comment]
@joewalsh Thanks for reviewing. Can you merge this if all is good?

**Pull request merged**
