### PR TITLE
Podfile/project clean-ups and code coverage fix

### PR DESCRIPTION
**Pull request by bgerstle**
Hey guys! :wave: 

As @coreyfloyd predicted :crystal_ball:, my first contribution as a volunteer is about code coverage.  @stevepeak pinged me about something, and in my investigation, I discovered that someone had accidentally disabled "legacy" code coverage file generation.  Let's see if codecov picks up our non-Swift test coverage and bumps the project back up to 26% (observed coverage in Xcode).

I also went ahead and tidied up a couple other things.

### CODE REVIEW

**Comment by bgerstle** [comment]
uh [wut](https://travis-ci.org/wikimedia/wikipedia-ios/builds/116805222#L8685)

> Testing failed:
'SSBaseTableCell.h' file not found
** TEST FAILED **
> The command "bundle exec fastlane $FL_ARGS" exited with 0.

**Comment by bgerstle** [comment]
ah, [much better](https://codecov.io/github/wikimedia/wikipedia-ios/Wikipedia/Code?ref=6f0e87069aefad4a94c4b07ed742337151a840d0)

image

...but still not 26%. maybe there's some code being filtered in codecov that Xcode is including..._shrugs_

**Comment by montehurd** [comment]
@bgerstle Brian! You are awesome! :)

**Comment by stevepeak** [comment]
Nice job @bgerstle! :+1:

**Comment by coreyfloyd** [comment]
He's baaaaaaaaak. 👻

**Comment by coreyfloyd** [comment]
Seriously thanks @bgerstle @stevepeak. I noticed this but have been running around the past week and haven't had time to look into it.

**Pull request merged**
