### PR TITLE
Add profile view to article

### PR DESCRIPTION
**Pull request by l-olson1214**
**Phabricator:** 

### Notes
* 

### Test Steps
1. Open app
2. Navigate to any article
3. Ensure icon appears in upper righthand corner
4. Tap icon
5. Ensure page appears and is dismissable

### Screenshots/Videos
Simulator Screenshot - iPhone 15 Pro - 2024-09-19 at 09 55 36
Simulator Screenshot - iPhone 15 Pro - 2024-09-19 at 09 55 39

### CODE REVIEW

**Review by tonisevener — CHANGES_REQUESTED** [review]
@l-olson1214 Code looks good. I found a couple of bugs, can you look into fixing them? I can merge this first if you'd rather do it as a follow-on, just let me know.

1. The article badge doesn't react immediately when I go back from notifications.

https://github.com/user-attachments/assets/4874e8f7-9dda-4a1c-9dc2-687d588c2f80

2. The profile icon doesn't react immediately when changing the theme on article.

https://github.com/user-attachments/assets/51ca351d-2c1f-4916-bed7-6c6d29953321

**Comment by l-olson1214** [comment]
> @l-olson1214 Code looks good. I found a couple of bugs, can you look into fixing them? I can merge this first if you'd rather do it as a follow-on, just let me know.
> 
> 1. The article badge doesn't react immediately when I go back from notifications.
> 
>  badge.bug.mov 
> 2. The profile icon doesn't react immediately when changing the theme on article.
> 
>  icon.color.bug.mov

@tonisevener  - I got the colors and added it on refresh and view will appear - it did seem a little funky for a second with notifications but I'm not 100% sure. Am I still missing something?

**Comment by tonisevener** [comment]
> @tonisevener - I got the colors and added it on refresh and view will appear - it did seem a little funky for a second with notifications but I'm not 100% sure. Am I still missing something?

It's working for me, from what I can tell. Actually I found that the bare-minimum calls to `setupSearchAndProfile` that you need now are the ones in `viewWillAppear` (this allows the notifications count to be checked and the badge state updated after tapping "Back") and the call in `applyTheme` (this fixes the color when the theme changes). Can you delete the other calls and let me know if it still works on your end?

**Comment by l-olson1214** [comment]
> > @tonisevener - I got the colors and added it on refresh and view will appear - it did seem a little funky for a second with notifications but I'm not 100% sure. Am I still missing something?
> 
> It's working for me, from what I can tell. Actually I found that the bare-minimum calls to `setupSearchAndProfile` that you need now are the ones in `viewWillAppear` (this allows the notifications count to be checked and the badge state updated after tapping "Back") and the call in `applyTheme` (this fixes the color when the theme changes). Can you delete the other calls and let me know if it still works on your end?

Got it @tonisevener ! Seems to be working :)

**Review by tonisevener — APPROVED** [review]

**Pull request merged**
