### PR TITLE
Minor build & project tweaks

### PR DESCRIPTION
**Pull request by bgerstle**
- update-qqq will be run outside of build pipeline (maybe as a jenkins job w/ TWN sync one day)
- reduce project down to 6 warnings!!... by wrapping deprecation warnings & TODOs! (y/w @coreyfloyd)
  - when `WMF_SHOW_TECH_DEBT_WARNINGS` is enabled, we get deprecation & TODOs like:
image
  - otherwise... silence

### CODE REVIEW

**Comment by montehurd** [comment]
Interesting about the location setting and file creation - I think Corey ran in to that.

**Comment by montehurd** [comment]
We've moved lots of things around lately - will prob want to test that grunt and web scripts still do their thing...

**Comment by bgerstle** [comment]
@montehurd still works! (2e32e98) makes sense, given that we didn't move the assets or www folders

**Comment by bgerstle** [comment]
if any web stuff crops up we can revert the commit, but figured might as well update now

**Comment by coreyfloyd** [comment]
:+1:

**Pull request merged**
