### PR TITLE
Make article equality check title, instead of just site

### PR DESCRIPTION
**Pull request by bgerstle**
Not checking article titles during equality checks was causing issues with partially-populated articles (e.g. filled with data from a search result).  Long-term, this would be a non-issue since we plan to use separate model objects for those responses, but it was good that it surfaced this oversight.

### CODE REVIEW

**Comment by bgerstle** [comment]
@brion would you mind clarifying your rationale behind omitting titles from equality checks in `MWKArticle`? I can't think of any cases where considering articles with unequal titles would be desirable, but I'm not a battle-hardened MW veteran yet ;-).

**Comment by brion** [comment]
Must've been an oversight, over reliance on unit tests in the coding. ;)

**Comment by coreyfloyd** [comment]
:+1: looks good - just waiting on travis

**Comment by coreyfloyd** [comment]
just fixed a project file conflict… merging without waiting for new tests to run (living on the edge)

**Pull request merged**
