### PR TITLE
Move tweaks to settings menu.

### PR DESCRIPTION
**Pull request by montehurd**
- No more shake to show tweaks menu.
- Added "Tweaks" entry to settings under "Debug".
- Removed some old un-used animation code, but refrained from other boyscouting on the Settings vc for now.

shake mov

### CODE REVIEW

**Comment by bgerstle** [comment]
looks good! :+1: what would you think about changing the "Tweaks" to something more intuitive like "Developer Settings"?

**Comment by bgerstle** [comment]
@montehurd did you also test that the button is hidden in release builds?

**Comment by montehurd** [comment]
@bgerstle oh i like "Developer settings" :)

**Comment by montehurd** [comment]
Confirmed it's hidden on release builds:

screen shot 2016-02-02 at 11 26 02 am

**Comment by bgerstle** [comment]
:+1: will merge once travis passes (again)

**Pull request merged**
