### PR TITLE
implementing feature request: https://phabricator.wikimedia.org/T172990

### PR DESCRIPTION
**Pull request by aclaussen1**
In appearance settings, users can now set tables in articles to automatically be opened

### CODE REVIEW

**Comment by aclaussen1** [comment]
Is everything okay here? @joewalsh

**Comment by joewalsh** [comment]
@aclaussen1 Thanks for submitting this PR! With the work for https://phabricator.wikimedia.org/T175322 the way we handle table collapsing has changed, so this PR should be updated to work with the new method. @montehurd should be able to point you in the right direction. Also, our product and design teams will review the implementation and decide when we want to incorporate this into a release. Thanks again for contributing!

**Comment by montehurd** [comment]
@aclaussen1 

Sorry about my [PR](https://github.com/wikimedia/wikipedia-ios/pull/1890) changing the bits you were trying to modify! We had to tweak the way we load sections for performance (and other) reasons.

Without knowing the design team's requirements for letting users opt-out of table collapsing I don't know what changes will be needed to bring your PR up to date. That is, if they say something like, "_If a user expands any table just leave all other tables expanded too, until they collapse another one, at which time just leave all tables collapsed_" then we won't need a setting at all.

Design should let us know soon how to proceed :) Thanks again for the PR!!!

**Comment by montehurd** [comment]
Hey @aclaussen1 

Design weighed in on [T172990](https://phabricator.wikimedia.org/T172990) and it was moved to `Ready for development`. 

I took a peek and added a [quick PR](https://github.com/wikimedia/wikipedia-ios/pull/1944) which will give you a [parameter](https://github.com/wikimedia/wikipedia-ios/pull/1944/files#diff-09845a6cbced47f41201dbc4de3fbc61R223) you can change from native-land which will cause the table collapsing JS to `collapseTablesInitially` as needed.

Once my PR gets merged (hopefully early next week - the other reviewers have the next couple days off) you should have what you need. Let me know if anything is missing or if we can help.

**Comment by aclaussen1** [comment]
@montehurd Thanks! I'll keep an eye on your PR.

The design team added what appears to be a new icon for this feature. https://zpl.io/adR9AR2
It doesn't appear that these icons have been added to Images.xcassets on the develop branch. Since I am not a member of the organization I cannot access Zeplin so I myself won't be able to add the image files. 

I could do this myself but it seems I'd need to be added to Zeplin. On Zeplin my username is aclaussen1 and my email is aclaussen1@student.gsu.edu. Otherwise someone else will need to add it.

Thanks!

**Comment by montehurd** [comment]
@aclaussen1 

> The design team added what appears to be a new icon for this feature. https://zpl.io/adR9AR2
It doesn't appear that these icons have been added to Images.xcassets on the develop branch. 

Oh sorry about that! Doesn't look like I can add to the Zeplin acct, but in the mean time I was able to log in myself and get the asset for you:

[tables-expand.pdf](https://github.com/wikimedia/wikipedia-ios/files/1497536/tables-expand.pdf)

**Comment by aclaussen1** [comment]
@montehurd thanks!

**Comment by joewalsh** [comment]
@aclaussen1 the other PR has been merged so you can use the new `window.wmf.sections.collapseTablesInitially` parameter. Also, it looks like there's a merge conflict in the localization files due to the new strings. After updating from `develop`, build and run in xcode to update all of the localization files before committing the merge.

**Comment by joewalsh** [comment]
@aclaussen1 we're planning on scheduling this into our next release, so I went ahead and finished up the integration in #1967. Thanks for your contribution! Looking forward to having this feature in the app.

**Pull request merged**
