### PR TITLE
Fix continue reading

### PR DESCRIPTION
**Pull request by coreyfloyd**
Just need to use the open article title from user defaults

### CODE REVIEW

**Comment by bgerstle** [comment]
image

**Comment by bgerstle** [comment]
@coreyfloyd only problem is, I can't test w/ the tweak (feed never shows continue reading since I have to pop back to the feed to see the last open article, which removes the setting, which hides continue reading).  should we update the "continue reading tweak" to always go to home/explore root on launch?

**Comment by coreyfloyd** [comment]
@bgerstle added a tweak to turn off the showing the last open article

**Comment by bgerstle** [comment]
image

**Comment by bgerstle** [comment]
:+1:

**Pull request merged**
