### PR TITLE
Fix inappropriate truncation of image filenames/extensions

### PR DESCRIPTION
**Pull request by mdholloway**
Bug: T104576

### CODE REVIEW

**Comment by bgerstle** [comment]
thanks @mdholloway! would you mind adding some tests (or comments) to explain what this fixes? happy to pair with you on it tomorrow or tuesday

**Comment by bgerstle** [comment]
or, if you're not up for writing ObjC/Swift, pointers to test cases or example strings & outputs would be nice so we can add the tests

**Comment by mdholloway** [comment]
Will do!  I've been expanding my horizons with some iOS stuff this weekend; writing a test or two would be good practice.

**Comment by mdholloway** [comment]
Any idea why I'd be getting an "'OCHamcrest/OCHamcrest.h' file not found" error when I try to run the tests?  It's definitely there in the project...

**Comment by mdholloway** [comment]
I added a test but I figure I'll wait until I can get the tests running locally to verify it before adding it to the PR.  

But to describe what the patch does, the old regex was capturing all non-period characters after the (optional) size prefix, followed by a period and all non-period characters following that period until another period was encountered.  I think this was intended to truncate all file extensions beyond the first.  But this was being fooled by filenames containing periods into truncating too early.  So what I did is to add a check so that the expression captures:
1.  Up to any number of non-period characters, then
2.  Up to any number of instances of a pattern consisting of a period followed by four or more characters other than another period or the end of a line, then
3.  A period followed by any number of non-period characters (that will necessarily be three or fewer).

**Comment by bgerstle** [comment]
@mdholloway great thanks! i have a fix on #161 for the false compiler errors, and I think I know what's causing the funny coverage data. going to re-run the build to confirm, but otherwise this is good to merge :+1:

**Comment by mdholloway** [comment]
Sweet!

**Pull request merged**
