### PR TITLE
Article fetching/refreshing logic

### PR DESCRIPTION
**Pull request by bgerstle**
Phab: [T121439](https://phabricator.wikimedia.org/T121439)

---

This is an implementation of the (amended) "new approach" described in the above Phab ticket which, given an article is cached (with a stored revision ID), will:

- Fetch latest revision
  - On success, check if the cached article's revision matches
    - If it matches, return cached article
    - If it doesn't match, fetch the latest revision
  - On failure, return cached article as fallback

## Open questions
See Phab ticket for open questions about prompt UI/UX & business logic.

## Dev notes
As part of doing this I refactored some article container code to remove the immediate download of the latest data (first few commits).  This was necessary no matter what fetching/refreshing logic we wanted to do down the road.

I also took a moment to DRY up & fix the article progress indication logic (b0df1e4d) & empty view display (7b84d78).  Should be more straight-forward now, and I checked the following error flows:

- [x] Tapping a link/feed item while offline (regression test for error view jumping)
- [x] Errors in other contexts
  - [editing](https://cloud.githubusercontent.com/assets/444217/11874174/5b821e58-a4ac-11e5-9ae0-7dfd50440c64.png)
  - [search](https://cloud.githubusercontent.com/assets/444217/11874193/72b3d8fa-a4ac-11e5-982f-84c08eb0c05c.png)
  - [feed](https://cloud.githubusercontent.com/assets/444217/11874300/f05a27b4-a4ac-11e5-828c-51e8fd70ee72.png)
- [x] not showing progress indicator for cached articles (see demo video/GIF)
- [x] proper progress progression for uncached articles
  - [x] on WiFi (see demo video/GIF)
  - [x] [w/ NLC](https://cloud.githubusercontent.com/assets/444217/11874458/cb6a4708-a4ad-11e5-93ed-83623adb58eb.gif)
    - _side note: there appears to be an issue where the header image gallery won't retry to download images (or display errors when they time out)_

### CODE REVIEW

**Comment by bgerstle** [comment]
@nirzar have a look at the demo GIF/video and ping me if/when you want to discuss the design

**Comment by coreyfloyd** [comment]
@bgerstle all looks pretty solid. I made comments about the specific solution on the ticket itself. But all the revision work and refactors look good.

**Comment by bgerstle** [comment]
thanks @coreyfloyd I'd like to add some tests before merging, but wanted to get prelim feedback before I put more work into this approach.

**Comment by coreyfloyd** [comment]
@bgerstle this is all looking really good - I like the changes/simplification of the fetch logic in the article VC - deferring fetching until viewDidAppear makes it a lot cleaner.

**Comment by bgerstle** [comment]
:smile:

**Comment by bgerstle** [comment]
:-1: there's an issue w/ redundant read more fetches, fixing now

**Comment by coreyfloyd** [comment]
doh!

**Comment by bgerstle** [comment]
@coreyfloyd @montehurd should be ready to go now

**Comment by montehurd** [comment]
SHIP IT!  :+1:

**Pull request merged**
