### PR TITLE
Add farsi to Persian for language selector bug

### PR DESCRIPTION
**Pull request by Edgecombe27**
screen shot 2018-03-01 at 11 36 54 am

### CODE REVIEW

**Comment by montehurd** [comment]
Thanks for the PR! We'll try to get to this ASAP - in a crunch presently :)

**Comment by coreyfloyd** [comment]
Is there a reason to update NotificationMessage in this patch? is that from upstream?

**Comment by montehurd** [comment]
@coreyfloyd the NotificationMessage bits look unrelated.

@Edgecombe27 was that commit accidentally pushed?

**Comment by Edgecombe27** [comment]
@montehurd my bad, the changes have been reverted

**Comment by Edgecombe27** [comment]
@montehurd my bad, I reverted the changes.

**Comment by Edgecombe27** [comment]
@coreyfloyd I removed those changes they were unrelated.

**Comment by montehurd** [comment]
retest this please

**Comment by montehurd** [comment]
@Edgecombe27 ^ that's just to re-trigger our build system - you don't need to re-test :)

**Pull request merged**
