### PR TITLE
Fix places search suggestion & empty view layout issues

### PR DESCRIPTION
**Pull request by joewalsh**
https://phabricator.wikimedia.org/T202800
https://phabricator.wikimedia.org/T202799

### CODE REVIEW

**Comment by montehurd** [comment]
one slight difference i noticed is we fade out the empty view image for save and history when rotating landscape, but this pr shrinks the image, which looks a bit odd...

**Comment by montehurd** [comment]
jenkins retest this please

**Comment by montehurd** [comment]
jenkins retest this please

**Comment by joewalsh** [comment]
retest this please

**Pull request merged**
