### PR TITLE
Bug/license icons/T127377

### PR DESCRIPTION
**Pull request by joewalsh**
https://phabricator.wikimedia.org/T127377

### CODE REVIEW

**Comment by coreyfloyd** [comment]
👍

**Comment by montehurd** [comment]
Crashes on iOS 9 when tapping lead image in article.

**Comment by joewalsh** [comment]
@montehurd that doesn't repro for me- could you provide the specific article and config?
I tested `Diamonds (Rihanna Song)`, `Arnold Palmer` and `Toys in the Attic (album)` on 9.3 6S sim.

**Comment by montehurd** [comment]
@joewalsh hmm i tested those first 2 articles you mentioned too... double checking...

**Comment by montehurd** [comment]
doing clean build to re-test (was using iPhone 6s - iOS 9.3 sim)

**Comment by montehurd** [comment]
Ya, still happening every time after clean build:

2016-09-27 10:54:45.807 Wikipedia Debug[77432:7450363] *** Assertion failure in -[MASViewConstraint install], /Users/montehurd/wikipedia-ios/Pods/Masonry/Masonry/MASViewConstraint.m:338
2016-09-27 10:54:45.833 Wikipedia Debug[77432:7450363] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'couldn't find a common superview for <UIImageView: 0x7f8d8b55b840; frame = (0 0; 16 16); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x7f8d8d9e0600>> and <UIStackView: 0x7f8d8d9a92f0; frame = (0 0; 1000 1000); opaque = NO; autoresize = RM+BM; userInteractionEnabled = NO; layer = <CATransformLayer: 0x7f8d8fee9010>>'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000011393ad85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001133aedeb objc_exception_throw + 48
	2   CoreFoundation                      0x000000011393abea +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x000000010fe0ed5a -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   Masonry                             0x000000011027dd34 -[MASViewConstraint install] + 2308
	5   Masonry                             0x0000000110274f1e -[MASCompositeConstraint install] + 414
	6   Masonry                             0x00000001102786fb -[MASConstraintMaker install] + 1035
	7   Masonry                             0x0000000110283dcb -[UIView(MASAdditions) mas_makeConstraints:] + 155
	8   Wikipedia Debug                     0x000000010eb9c5c3 -[WMFImageGalleryDetailOverlayView newImageViewForLicenseWithCode:] + 547
	9   Wikipedia Debug                     0x000000010eb9cdc2 -[WMFImageGalleryDetailOverlayView setLicense:owner:] + 1170
	10  Wikipedia Debug                     0x000000010eb7f04e -[WMFImageGalleryViewController photosViewController:captionViewForPhoto:] + 910
	11  NYTPhotoViewer                      0x000000011041f414 -[NYTPhotosViewController updateOverlayInformation] + 1348
	12  Wikipedia Debug                     0x000000010eb8109b -[WMFArticleImageGalleryViewController imageInfoController:didFetchBatch:] + 395
	13  Wikipedia Debug                     0x000000010ebbe2c5 __37-[WMFImageInfoController fetchBatch:]_block_invoke_3 + 373
	14  libdispatch.dylib                   0x0000000114c57d9d _dispatch_call_block_and_release + 12
	15  libdispatch.dylib                   0x0000000114c783eb _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x0000000114c601ef _dispatch_main_queue_callback_4CF + 1738
	17  CoreFoundation                      0x00000001138940f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	18  CoreFoundation                      0x0000000113855b99 __CFRunLoopRun + 2073
	19  CoreFoundation                      0x00000001138550f8 CFRunLoopRunSpecific + 488
	20  GraphicsServices                    0x0000000117257ad2 GSEventRunModal + 161
	21  UIKit                               0x0000000110c5cf09 UIApplicationMain + 171
	22  Wikipedia Debug                     0x000000010eb5b689 main + 105
	23  libdyld.dylib                       0x0000000114cac92d start + 1
	24  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by joewalsh** [comment]
@montehurd that still doesn't repro for me, but I committed a change based on the exception you're seeing. let me know if that fixed it.

**Comment by montehurd** [comment]
Yes it fixed the crash! However it added 9 constraint breakage alerts:

2016-09-27 13:35:10.150 Wikipedia Debug[1215:7609394] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x7fbb6c8639e0 NYTPhotosOverlayView:0x7fbb6c867e90.width == 0>",
    "<NSLayoutConstraint:0x7fbb6c868020 UIButton:0x7fbb6c870010.width == 26>",
    "<NSLayoutConstraint:0x7fbb6cb9f920 UIButton:0x7fbb6c870010.leading >= UIStackView:0x7fbb6cb9ed50.trailing + 10>",
    "<NSLayoutConstraint:0x7fbb6cb9f970 UIButton:0x7fbb6c870010.trailing == UILabel:0x7fbb6cb9b170.trailing>",
    "<NSLayoutConstraint:0x7fbb6cb9fa60 UILabel:0x7fbb6cb9b170.leading == WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.leading + 20>",
    "<NSLayoutConstraint:0x7fbb6cb9fab0 WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.trailing == UILabel:0x7fbb6cb9b170.trailing + 20>",
    "<NSLayoutConstraint:0x7fbb6cb9fbf0 UIButton:0x7fbb6cb9c8d0.leading == UILabel:0x7fbb6cb9b170.leading>",
    "<NSLayoutConstraint:0x7fbb6cb9fce0 UIButton:0x7fbb6cb9c8d0.trailing == UIStackView:0x7fbb6cb9ed50.trailing>",
    "<NSLayoutConstraint:0x7fbb6cb12eb0 WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.width == NYTPhotosOverlayView:0x7fbb6c867e90.width>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fbb6c868020 UIButton:0x7fbb6c870010.width == 26>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-09-27 13:35:10.152 Wikipedia Debug[1215:7609394] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x7fbb6c8639e0 NYTPhotosOverlayView:0x7fbb6c867e90.width == 0>",
    "<NSLayoutConstraint:0x7fbb6cb9f920 UIButton:0x7fbb6c870010.leading >= UIStackView:0x7fbb6cb9ed50.trailing + 10>",
    "<NSLayoutConstraint:0x7fbb6cb9f970 UIButton:0x7fbb6c870010.trailing == UILabel:0x7fbb6cb9b170.trailing>",
    "<NSLayoutConstraint:0x7fbb6cb9fa60 UILabel:0x7fbb6cb9b170.leading == WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.leading + 20>",
    "<NSLayoutConstraint:0x7fbb6cb9fab0 WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.trailing == UILabel:0x7fbb6cb9b170.trailing + 20>",
    "<NSLayoutConstraint:0x7fbb6cb9fbf0 UIButton:0x7fbb6cb9c8d0.leading == UILabel:0x7fbb6cb9b170.leading>",
    "<NSLayoutConstraint:0x7fbb6cb9fce0 UIButton:0x7fbb6cb9c8d0.trailing == UIStackView:0x7fbb6cb9ed50.trailing>",
    "<NSLayoutConstraint:0x7fbb6cb12eb0 WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.width == NYTPhotosOverlayView:0x7fbb6c867e90.width>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fbb6cb9f920 UIButton:0x7fbb6c870010.leading >= UIStackView:0x7fbb6cb9ed50.trailing + 10>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-09-27 13:35:10.154 Wikipedia Debug[1215:7609394] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x7fbb6c8639e0 NYTPhotosOverlayView:0x7fbb6c867e90.width == 0>",
    "<NSLayoutConstraint:0x7fbb6cb9fa60 UILabel:0x7fbb6cb9b170.leading == WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.leading + 20>",
    "<NSLayoutConstraint:0x7fbb6cb9fab0 WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.trailing == UILabel:0x7fbb6cb9b170.trailing + 20>",
    "<NSLayoutConstraint:0x7fbb6cb12eb0 WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.width == NYTPhotosOverlayView:0x7fbb6c867e90.width>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fbb6cb9fab0 WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.trailing == UILabel:0x7fbb6cb9b170.trailing + 20>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-09-27 13:35:10.156 Wikipedia Debug[1215:7609394] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x7fbb6c871470 NYTPhotosOverlayView:0x7fbb6c867e90.height == 0>",
    "<NSLayoutConstraint:0x7fbb6c870320 UIButton:0x7fbb6c870010.height == 26>",
    "<NSLayoutConstraint:0x7fbb6cb9f8d0 UIButton:0x7fbb6c870010.top == UILabel:0x7fbb6cb9b170.bottom + 12>",
    "<NSLayoutConstraint:0x7fbb6cb9f9c0 WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.bottom == UIButton:0x7fbb6c870010.bottom + 12>",
    "<NSLayoutConstraint:0x7fbb6cb9fa10 UILabel:0x7fbb6cb9b170.top >= WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.top + 50>",
    "<NSLayoutConstraint:0x7fbb6cb0e2d0 WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.height <= NYTPhotosOverlayView:0x7fbb6c867e90.height * 0.3>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fbb6c870320 UIButton:0x7fbb6c870010.height == 26>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-09-27 13:35:10.157 Wikipedia Debug[1215:7609394] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x7fbb6c871470 NYTPhotosOverlayView:0x7fbb6c867e90.height == 0>",
    "<NSLayoutConstraint:0x7fbb6cb9cb70 UIButton:0x7fbb6cb9c8d0.height == 26>",
    "<NSLayoutConstraint:0x7fbb6cb9fa10 UILabel:0x7fbb6cb9b170.top >= WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.top + 50>",
    "<NSLayoutConstraint:0x7fbb6cb9fc40 WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.bottom == UIButton:0x7fbb6cb9c8d0.bottom + 12>",
    "<NSLayoutConstraint:0x7fbb6cb9fc90 UIButton:0x7fbb6cb9c8d0.top == UILabel:0x7fbb6cb9b170.bottom + 12>",
    "<NSLayoutConstraint:0x7fbb6cb0e2d0 WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.height <= NYTPhotosOverlayView:0x7fbb6c867e90.height * 0.3>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fbb6cb9cb70 UIButton:0x7fbb6cb9c8d0.height == 26>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-09-27 13:35:10.159 Wikipedia Debug[1215:7609394] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x7fbb6c871470 NYTPhotosOverlayView:0x7fbb6c867e90.height == 0>",
    "<NSLayoutConstraint:0x7fbb6cb9fa10 UILabel:0x7fbb6cb9b170.top >= WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.top + 50>",
    "<NSLayoutConstraint:0x7fbb6cb9fc40 WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.bottom == UIButton:0x7fbb6cb9c8d0.bottom + 12>",
    "<NSLayoutConstraint:0x7fbb6cb9fc90 UIButton:0x7fbb6cb9c8d0.top == UILabel:0x7fbb6cb9b170.bottom + 12>",
    "<NSLayoutConstraint:0x7fbb6cb0e2d0 WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.height <= NYTPhotosOverlayView:0x7fbb6c867e90.height * 0.3>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fbb6cb9fc90 UIButton:0x7fbb6cb9c8d0.top == UILabel:0x7fbb6cb9b170.bottom + 12>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-09-27 13:35:10.160 Wikipedia Debug[1215:7609394] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<MASLayoutConstraint:0x7fbb6cba0b30 UIImageView:0x7fbb6cb0b670.top == UIStackView:0x7fbb6cb9ed50.top>",
    "<MASLayoutConstraint:0x7fbb6cba0e20 UIImageView:0x7fbb6cb0b670.bottom == UIStackView:0x7fbb6cb9ed50.bottom>",
    "<NSAutoresizingMaskLayoutConstraint:0x7fbb6c871470 NYTPhotosOverlayView:0x7fbb6c867e90.height == 0>",
    "<NSLayoutConstraint:0x7fbb6cb9fa10 UILabel:0x7fbb6cb9b170.top >= WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.top + 50>",
    "<NSLayoutConstraint:0x7fbb6cb9fb00 WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.bottom == UIStackView:0x7fbb6cb9ed50.bottom + 12>",
    "<NSLayoutConstraint:0x7fbb6cb9fb50 UIStackView:0x7fbb6cb9ed50.top == UILabel:0x7fbb6cb9b170.bottom + 12>",
    "<NSLayoutConstraint:0x7fbb6cb0e2d0 WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.height <= NYTPhotosOverlayView:0x7fbb6c867e90.height * 0.3>"
)

Will attempt to recover by breaking constraint 
<MASLayoutConstraint:0x7fbb6cba0e20 UIImageView:0x7fbb6cb0b670.bottom == UIStackView:0x7fbb6cb9ed50.bottom>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-09-27 13:35:10.161 Wikipedia Debug[1215:7609394] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x7fbb6c871470 NYTPhotosOverlayView:0x7fbb6c867e90.height == 0>",
    "<NSLayoutConstraint:0x7fbb6cb9f8d0 UIButton:0x7fbb6c870010.top == UILabel:0x7fbb6cb9b170.bottom + 12>",
    "<NSLayoutConstraint:0x7fbb6cb9f9c0 WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.bottom == UIButton:0x7fbb6c870010.bottom + 12>",
    "<NSLayoutConstraint:0x7fbb6cb9fa10 UILabel:0x7fbb6cb9b170.top >= WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.top + 50>",
    "<NSLayoutConstraint:0x7fbb6cb0e2d0 WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.height <= NYTPhotosOverlayView:0x7fbb6c867e90.height * 0.3>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fbb6cb9f8d0 UIButton:0x7fbb6c870010.top == UILabel:0x7fbb6cb9b170.bottom + 12>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-09-27 13:35:10.162 Wikipedia Debug[1215:7609394] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x7fbb6c871470 NYTPhotosOverlayView:0x7fbb6c867e90.height == 0>",
    "<NSLayoutConstraint:0x7fbb6cb9fa10 UILabel:0x7fbb6cb9b170.top >= WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.top + 50>",
    "<NSLayoutConstraint:0x7fbb6cb9fb00 WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.bottom == UIStackView:0x7fbb6cb9ed50.bottom + 12>",
    "<NSLayoutConstraint:0x7fbb6cb9fb50 UIStackView:0x7fbb6cb9ed50.top == UILabel:0x7fbb6cb9b170.bottom + 12>",
    "<NSLayoutConstraint:0x7fbb6cb0e2d0 WMFImageGalleryDetailOverlayView:0x7fbb6cb9b910.height <= NYTPhotosOverlayView:0x7fbb6c867e90.height * 0.3>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fbb6cb9fb50 UIStackView:0x7fbb6cb9ed50.top == UILabel:0x7fbb6cb9b170.bottom + 12>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-09-27 13:35:10:507 Wikipedia Debug[main] -[WMFImageInfoController fetchBatch:]#L185 D: Batch {0, 7} has already been fetched.

**Comment by montehurd** [comment]
Looks like the cause is 
"&lt;NSAutoresizingMaskLayoutConstraint:0x7fbb6c8639e0 NYTPhotosOverlayView:0x7fbb6c867e90.width == 0&gt;" 
and 
"&lt;NSAutoresizingMaskLayoutConstraint:0x7fbb6c871470 NYTPhotosOverlayView:0x7fbb6c867e90.height == 0&gt;"

**Comment by joewalsh** [comment]
@montehurd as long as the layout is fine, I think we should merge with those constraint errors and look at fixing the issue inside of NYTPhotosOverlayView

**Comment by joewalsh** [comment]
(since we don't have access to NYTPhotosOverlayView, we just return an overlay view for the component to use)

**Comment by montehurd** [comment]
@joewalsh sounds good 👍

**Comment by montehurd** [comment]
Oops I just tapped on the user name at the bottom of this image in the Tangent article and got a crash...

screen shot 2016-09-27 at 1 51 35 pm

**Comment by montehurd** [comment]
Also happened on tapping user name on first image in Tangent article.

**Comment by joewalsh** [comment]
@montehurd it's an assertion failure checking for a non-nil URL. The same issue happens on develop, so it's separate from this PR.

**Comment by montehurd** [comment]
@joewalsh gotcha. i'll create a ticket

**Comment by montehurd** [comment]
Made a ticket: https://phabricator.wikimedia.org/T146831

**Comment by montehurd** [comment]
@joewalsh sorry about all the confusion over the assert. that's what i get for skipping lunch. nice work.

**Pull request merged**
