### PR TITLE
Add Jonatan Svensson Glad to contributors.

### PR DESCRIPTION
**Pull request by montehurd**
@josve05a Added you to contributor list. Is this ok? Name correct? (From your Github page)

### CODE REVIEW

**Comment by bgerstle** [comment]
:clap:

**Comment by josve05a** [comment]
That's my real name, yes (if need to be shorter you can use Jonatan S. Glad or just Jonatan Glad). Not sure that my super-tiny contribution warrants this however.

**Comment by bgerstle** [comment]
> Not sure that my super-tiny contribution warrants this however.

No contribution is too small

**Comment by coreyfloyd** [comment]
just merging… stupid travis.

**Pull request merged**
