### PR TITLE
Make banner RTL

### PR DESCRIPTION
**Pull request by coreyfloyd**
https://phabricator.wikimedia.org/T121423

screen shot 2015-12-15 at 1 30 55 pm

### CODE REVIEW

**Comment by bgerstle** [comment]
@coreyfloyd FYI you can update specific pods by doing `[bundle exec] pod update $POD_NAME` if you don't want to update all our pods (e.g. just TSGMessage)

**Comment by bgerstle** [comment]
@coreyfloyd did TSMessage use Masonry before this change?

**Comment by coreyfloyd** [comment]
@bgerstle no - I added it (it wasn't auto layout based before)

**Comment by bgerstle** [comment]
@coreyfloyd that's OK for now, but I would expect that adding a dependency to TSMessage could be a potential blocker for merging this work upstream (since it increases the integration size). Not a problem for us since we're already using Masonry.

**Comment by bgerstle** [comment]
ah crap. @coreyfloyd the visual are tests are failing because of something i did in my fork of FBSnapshotTestCase (which you grabbed when updating all the Pods). I can try to fix it or you can back out the changes.

**Comment by coreyfloyd** [comment]
@bgerstle maybe we should specify the exact commit/branch/tag we should be using?

**Comment by montehurd** [comment]
Looking great, but I did notice the close button gets funky if the alert text is long:
screen shot 2015-12-15 at 11 26 55 am

Reference:
screen shot 2015-12-15 at 11 28 43 am

**Comment by montehurd** [comment]
@coreyfloyd Do we even need TSMessage any more? ;)

**Comment by bgerstle** [comment]
@montehurd @coreyfloyd regrets nothing

he regrets nothing

**Comment by coreyfloyd** [comment]
or everything

**Comment by bgerstle** [comment]
> or everything

:grimacing:

**Comment by coreyfloyd** [comment]
@montehurd @bgerstle should be good to go now

**Comment by bgerstle** [comment]
:+1:

**Comment by montehurd** [comment]
Opps wrong text alignment on iOS 8:

screen shot 2015-12-15 at 2 16 13 pm

iOS 9 is fine:
screen shot 2015-12-15 at 2 17 20 pm

**Comment by coreyfloyd** [comment]
@montehurd iOS 8 should be good now

**Comment by bgerstle** [comment]
lgtm :+1: : 
image

**Pull request merged**
