### PR TITLE
Dynamic type follow up tweaks 

### PR DESCRIPTION
**Pull request by montehurd**
2nd pass Dynamic Type - Tweaks from Carolyn:

- [x] Spacing tweaks to WMFArticlePreviewCollectionViewCell.
- [x] Fix for language cell layering on welcome language picker https://phabricator.wikimedia.org/T152156
- [x] 1st welcome screen "GET STARTED" button is reduced to "GET" when text size increases.
- [x] All welcome screen text layouts break at extended sizes.
- [x] Survey button explodes at large extended size.
- [x] In the News cell thumbnail is stretching.
- [x] History placeholder had "here" on own line.
- [ ] Hook up custom dynamic font in a few more places (with a couple more text size tweaks)

### CODE REVIEW

**Comment by montehurd** [comment]
We introduced an "In the News" thumbnail regression in the 1st Dynamic Type PR:

untitled mov

**Comment by montehurd** [comment]
We introduced an "In the News" thumbnail regression in the 1st Dynamic Type PR:

untitled mov

**Comment by joewalsh** [comment]
@montehurd can this be merged to roll a beta with the remaining checkmark as a follow on?

**Comment by montehurd** [comment]
@joewalsh ya for sure!

**Pull request merged**
