### PR TITLE
Update midnight widget refresh extension to use random time after midnight

### PR DESCRIPTION
**Pull request by staykids**
**Phabricator:** https://phabricator.wikimedia.org/T264881

### Notes
To possibly help mitigate spikes of traffic on the hour, randomize the requested refresh time of Picture of the day and On this day from midnight local time to some random minute and second within an hour after midnight local time.

### CODE REVIEW

**Comment by mcleinman** [comment]
Do we also need to update Picture of the Day?

**Comment by staykids** [comment]
I think Picture of the day is covered here – did you mean Top read? If so, I didn't touch the logic there because it doesn't explicitly use the midnight path and I'm not sure it's worth changing the "working" logic there before we understand if this approach is sufficient to mitigate the spikes in production or not.

**Comment by tonisevener** [comment]
> I think Picture of the day is covered here – did you mean Top read? If so, I didn't touch the logic there because it doesn't explicitly use the midnight path and I'm not sure it's worth changing the "working" logic there before we understand if this approach is sufficient to mitigate the spikes in production or not.

@staykids Interesting - I hadn't realized it didn't use the midnight path. Do you know how it's currently working now? It seems to update around midnight anyways for me.

**Comment by mcleinman** [comment]
> I think Picture of the day is covered here – did you mean Top read? If so, I didn't touch the logic there because it doesn't explicitly use the midnight path and I'm not sure it's worth changing the "working" logic there before we understand if this approach is sufficient to mitigate the spikes in production or not.

Guilty as charged. I saw two of three, and didn't pause long enough when writing that. Top Read looks up at the end of each day, right? (I'm a tad confused, but not important for now - it uses an `.atEnd` policy, but seems to set a date of now.)

**Review by mcleinman — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
