### PR TITLE
Convert search and saved pages to use table views

### PR DESCRIPTION
**Pull request by coreyfloyd**
2 parts of https://phabricator.wikimedia.org/T117806

### CODE REVIEW

**Comment by bgerstle** [comment]
:+1: looks good! porting doesn't seem too bad

**Comment by bgerstle** [comment]
@montehurd feast your :eyes: on this and administer :+1: / :-1:

**Comment by coreyfloyd** [comment]
@bgerstle oops - I thought this was already merged… so I just appended the saved pages work here as well… so much for keeping it small.

**Comment by montehurd** [comment]
Seems solid. I have a tiny constraint tweak but it can wait until this is merged. @bgerstle feel free to merge once your kvo tweak is in place.

**Pull request merged**
