### PR TITLE
Preloading web view when the article is loaded in the ArticleVC

### PR DESCRIPTION
**Pull request by coreyfloyd**
https://phabricator.wikimedia.org/T106107

### CODE REVIEW

**Comment by coreyfloyd** [comment]
Whoops… branch has the wrong ticket ID… correct one is in the description.

**Comment by bgerstle** [comment]
@coreyfloyd please rebase

**Comment by bgerstle** [comment]
@coreyfloyd also, can you please add QA notes to the ticket?

**Comment by bgerstle** [comment]
looks good, but found a bug:

1. Search for something
2. Tap "Read" _without_ making the result fullscreen first

### Expected
WebView presents modally and loads page content

### Actual
WebView presents modally and does nothing:

empty webview

**Comment by bgerstle** [comment]
:+1: can't reproduce w/ no read button!

**Pull request merged**
