### PR TITLE
Face detection fixes

### PR DESCRIPTION
**Pull request by bgerstle**
Bug: [T107110](https://phabricator.wikimedia.org/T107110)
Just when you thought you were safe... face detection gets broken! :rage4: 

So, I added lots of tests for the face detection logic in `MWKImage`, and manually verified that Barack's pretty face is nice and centered on his page.  Please review ASAP so we can resubmit.

### CODE REVIEW

**Comment by bgerstle** [comment]
@mhurd @coreyfloyd we won't be seeing Travis results on this PR (due to lacking `.travis.yml`) so for posterity:

> Test Suite 'All tests' passed at 2015-07-29 21:51:49 +0000.
	 Executed 166 tests, with 0 failures (0 unexpected) in 8.534 (8.930) seconds

**Comment by coreyfloyd** [comment]
looking good Mister Kotter! …as Vinny Barbarino would say, may he rest in peace.

**Comment by coreyfloyd** [comment]
:+1: almost forgot

**Comment by montehurd** [comment]
Seems to work!

**Pull request merged**
