### PR TITLE
Update location detail view

### PR DESCRIPTION
**Pull request by joewalsh**
simulator screen shot may 26 2017 12 27 39 pm
simulator screen shot may 26 2017 12 27 36 pm

https://phabricator.wikimedia.org/T166241

### CODE REVIEW

**Comment by amrox** [comment]
Looks reasonable, but can we get a description, screenshot or ticket? :)

**Comment by joewalsh** [comment]
@amrox ticket was in the branch name (same as other detail view updates), but added link & screenshots

**Comment by amrox** [comment]
Ah, didn’t notice the branch name, sorry

**Comment by montehurd** [comment]
@joewalsh For the `international federation` results, in the first screenshot the title is 3 lines and there's no wikidata description, but in the second screenshot the title is 2 lines with a description... is that difference intentional?

**Comment by joewalsh** [comment]
@montehurd that's autolayout preferring to use the space for the title label. Same thing happens in the explore feed. There may be updated designs for these cells at some point, at which time we could clarify expected behavior of the cells.

**Pull request merged**
