### PR TITLE
Adding Search tab

### PR DESCRIPTION
**Pull request by coreyfloyd**
Moved search to tab bar

https://phabricator.wikimedia.org/T107761

### CODE REVIEW

**Comment by montehurd** [comment]
There's whitespace at the top even when search is not showing...

**Comment by montehurd** [comment]
Also, one concern is that search is the most primary functionality of the app, and now instead of always being a single tap away (i.e. tap on the search bar and type), it's two taps away (tap on tab button, tap on search bar and type). This is a pretty huge UX change imo.

**Comment by coreyfloyd** [comment]
@montehurd thanks… forgot to push a change… forthcoming…

**Comment by montehurd** [comment]
ah cool

**Comment by montehurd** [comment]
Getting crash if I do a clean install and search for "d"...

**Comment by coreyfloyd** [comment]
@montehurd  huh? weird… looking

**Comment by coreyfloyd** [comment]
@montehurd got a stack trace? can't reproduce

**Pull request merged**
