### PR TITLE
Add compact horizontal sparkline grid to Top read widget

### PR DESCRIPTION
**Pull request by staykids**
**Phabricator:** https://phabricator.wikimedia.org/T262355

### Notes
Contains some design updates to the Top read widget.

* Adds grid to compact sparkline (visible in small and large sizes)
* Insets compact graph within grid
* Reduces width of small widget sparkline container

### Test Steps
1. Add Top read small and large widgets to iPhone X
2. Ensure horizontal grid lines are visible in both sizes, and that the small widget sparkline container proportionally matches small widget screenshot below

compact_grid

### CODE REVIEW

**Review by mcleinman — COMMENTED** [review]
Does this need another commit that is yet to be pushed up? I'm not seeing the sparkline show up on medium when I run this.

**Comment by staykids** [comment]
> Does this need another commit that is yet to be pushed up? I'm not seeing the sparkline show up on medium when I run this.

Thanks for checking on that – it's by design. The medium size top read widget should display reader count and not the sparkline. Here's a visual reference of how the widget should display per size:

top-read

**Comment by mcleinman** [comment]
🤦 Missed the specific call out to check that image for reference on **small** size.

**Review by mcleinman — APPROVED** [review]
Looks great! 

And I don't think I've said this to you yet, but I really like this one - I look at the large sized one every morning.

**Pull request merged**
