### PR TITLE
Fix for date field crash.

### PR DESCRIPTION
**Pull request by montehurd**
https://phabricator.wikimedia.org/T129912

https://rink.hockeyapp.net/manage/apps/152731/app_versions/40/crash_reasons/114070711

### CODE REVIEW

**Comment by coreyfloyd** [comment]
@montehurd do you know why the field is missing and are their any repercussions to just setting an arbitrary date?

Also should we just make the date optional? Is this just for showing the last modified date in the UI?

**Comment by montehurd** [comment]
@coreyfloyd lemme check a bit more...

**Comment by coreyfloyd** [comment]
👌

**Comment by coreyfloyd** [comment]
@montehurd couple questions:

1. What about displaying something in the last updated field of the article footer when the date is nil?
2. Is the hash succeeding when the date is nil?

**Comment by montehurd** [comment]
@coreyfloyd 
- hash seems fine 'cause it when it's nil the bitwise XOR sees it as 0 and thus the bitwise XOR doesn't change anything 
- checking the footer now...

**Comment by montehurd** [comment]
@coreyfloyd hmm yeah if the date is nil the footer says it was last edited 9 billion trillion zillion days ago... lemme fix that :)

**Comment by montehurd** [comment]
In rare case where the last modified date will be nil, per josh just show last modified `0 days ago` for now.

**Before:**
screen shot 2016-03-23 at 4 49 12 pm

**After:**
screen shot 2016-03-23 at 4 49 36 pm

**Comment by coreyfloyd** [comment]
:+1: will merge when done

**Pull request merged**
