### PR TITLE
Updating launch graphic

### PR DESCRIPTION
**Pull request by coreyfloyd**
You should see the background only on iPhones. iPad will be just a white background.

### CODE REVIEW

**Comment by bgerstle** [comment]
:+1: how are you hiding splash screen background on iPad? i didn't see a separate storyboard for iPad or any code that toggles it.

**Comment by montehurd** [comment]
:-1: 

Seeing flicker of the old splash screen 
- after new one appears and before welcome appears (hard to see in gif below - just a couple frames)
- after welcome disappears and before feed appears

untitled mov

**Comment by coreyfloyd** [comment]
@bgerstle size classes

**Comment by bgerstle** [comment]
@montehurd good catch.. @coreyfloyd it's still in the AppViewController storyboard. see "logo-onboarding"

**Comment by bgerstle** [comment]
@coreyfloyd got it for ya

**Comment by coreyfloyd** [comment]
@bgerstle was already doing it… don't want to just remove it and have a blank screen. Using the new splash work mark instead

**Comment by coreyfloyd** [comment]
@montehurd done

**Comment by bgerstle** [comment]
@coreyfloyd sorry, will check this now

**Comment by montehurd** [comment]
Tested on
- 4s
- iPad
- iPhone 6
- iPhone 6 iOS 8.4

Looks good.

:+1:

**Comment by bgerstle** [comment]
:+1: here as well

**Pull request merged**
