### PR TITLE
Feature/t106153/popup

### PR DESCRIPTION
**Pull request by coreyfloyd**
Implement pop up as non-transition API object.

https://phabricator.wikimedia.org/T106153

Straight forward… using standard animation methods… most of the logic came from the now defunct transition.

### CODE REVIEW

**Comment by coreyfloyd** [comment]
Removing lines of code… always good.

**Comment by coreyfloyd** [comment]
Also note… the preview isn't very useful right now… because of the image height… that is to be addressed later on with a restyle of the popup

**Comment by bgerstle** [comment]
we need to either handle rotation during "transition" or block it:
image

also, seeing this if I drag up too far:
image

**Comment by coreyfloyd** [comment]
@bgerstle note - it already bounces at the top…

Addressing rotation logic now

**Comment by coreyfloyd** [comment]
@bgerstle addressed concerns but labeled it a WIP - thinking that I am not sure if i should merge this before the popup view is redesigned… since the pop up is useless.

**Comment by bgerstle** [comment]
@coreyfloyd can we make a decision about what to do about popups? if this is blocked by redesigns i'd like to close this PR and move the phab task back to "needs design."

**Comment by coreyfloyd** [comment]
@bgerstle so for now, just to get this closed. I am disabling the popup  (basically feature flag off) until the design of the pop up view itself is re-accomplished.

Kaity is on the road today, but will try to get this closed out tomorrow.

**Comment by coreyfloyd** [comment]
Disabled - so removing the WIP so it can be merged

**Comment by bgerstle** [comment]
k, will re-review once travis confirms

**Pull request merged**
