### PR TITLE
Load home sections lazily (follow on to #339)

### PR DESCRIPTION
**Pull request by bgerstle**
Phab: [T121243](https://phabricator.wikimedia.org/T121243)

---

Explored this while working on #339.  It works, so here it is! See the laziness in [all its <strike>sloth</strike> glory](https://vid.me/tmei) on a 2G connection. In a nutshell, this:

- Adds a protocol for home section controllers to fetch their data _if needed_
- Modifies fetching section controllers to ensure their fetch methods are idempotent & remove their internal call to fetch when initialized

### Potential follow ons:
- Pre-fetching adjacent sections
- Aggregating section updates

### CODE REVIEW

**Comment by bgerstle** [comment]
@coreyfloyd @montehurd rebased after this PR's prequel was merged. now it only contains the new code

**Comment by montehurd** [comment]
Seems to work :)

**Comment by bgerstle** [comment]
@montehurd is that a +1 :wink:? @coreyfloyd can you please review?

**Comment by coreyfloyd** [comment]
:+1:

**Pull request merged**
