### PR TITLE
Add "wikipedia-official" URL scheme.

### PR DESCRIPTION
**Pull request by timonus**
This pull request introduces the "wikipedia-official" URL scheme to the Wikipedia app to differentiate it from others apps (like [Wikipanion](https://itunes.apple.com/us/app/wikipanion/id288349436?mt=8)) that also declare the "wikipedia://" URL scheme. This is useful for developers who want to reliably check whether or not the Wikipedia app is installed.

I'm planning on putting this to use in [Opener](https://github.com/timonus/OpenerManifest/blob/master/openerManifest-v3.json#L6232-L6238), which cannot differentiate between Wikipanion and Wikipedia being installed at the moment.

### CODE REVIEW

**Comment by KamranMackey** [comment]
LGTM :+1:

**Comment by joewalsh** [comment]
@timonus thanks for the PR! This change has some product implications, so a phabricator ticket has been created discuss the potential impact outside of a code review context: https://phabricator.wikimedia.org/T155565

**Comment by timonus** [comment]
@joewalsh ah, thanks for the heads up. Any way I can comment in there?

**Comment by joewalsh** [comment]
@timonus Sure! Unfortunately it's a bit of a complex account creation process: https://www.mediawiki.org/wiki/Phabricator/Help#Creating_your_account

**Comment by joewalsh** [comment]
@timonus thanks, this is good to go now! Will be in the next release - 5.4.0

**Comment by timonus** [comment]
Awesome! Thank you!

**Comment by timonus** [comment]
@joewalsh do you know when 5.4.0 will be released?

**Pull request merged**
