### PR TITLE
Remove MWKTitle and MWKSite

### PR DESCRIPTION
**Pull request by coreyfloyd**
This pr removes all references to MWKSite and MWKTitle in favor of the new NSURL methods. 

- [x] Replace all references to MWKTitle and MWKSite
- [x] Handle deserialization of Saved pages
- [x] Handle deserialization of history
- [x] Update Unit Tests
- [x] Update and verify deserialization of all former persisted classes
- [x] Rename all "domainURL" references to "siteURL"
- [x] File separate ticket to re-enable saved page fetcher tests

Out of scope for this PR:
- Any refactoring of logic that is now duplicative due to NSURLs being used for both title and site (refactoring such as this should be performed while boyscouting during normal development)
- Preserving the persisted feed data (The feed model will be completely changed during the feed refactor)

### CODE REVIEW

**Comment by coreyfloyd** [comment]
Do not merge before 5.0.5

**Comment by coreyfloyd** [comment]
@joewalsh @montehurd this PR has all the app code updated. It actually works - you can run the app and play with it.

Essentially I am updating unit tests. If you want to put this through its paces and/or report any bugs back - it is greatly appreciated.

**Comment by montehurd** [comment]
Getting `-[MWKTitle listIndex]: unrecognized selector` crash on startup iPhone 6 iOS 8 simulator:

<pre>
2016-07-14 16:03:50:543 Wikipedia Debug[main] -[BITHockeyManager(WMFExtensions) wmf_setupAndStart]#L36 E: app ID: 7138507aefac3ee74c295f75a0b857e4
2016-07-14 16:03:50.608 Wikipedia Debug[14456:1681033] [HockeySDK] -[BITHockeyManager startManager]/235 INFO: Starting HockeyManager
2016-07-14 16:03:50.608 Wikipedia Debug[14456:1681033] [HockeySDK] -[BITHockeyManager startManager]/241 INFO: Start CrashManager
2016-07-14 16:03:50.614 Wikipedia Debug[14456:1681033] [HockeySDK] WARNING: Detecting crashes is NOT enabled due to running the app with a debugger attached.
2016-07-14 16:03:50.619 Wikipedia Debug[14456:1681033] [HockeySDK] -[BITHockeyManager startManager]/277 INFO: Start FeedbackManager
2016-07-14 16:03:50.620 Wikipedia Debug[14456:1681033] [HockeySDK] -[BITHockeyManager startManager]/291 INFO: Start Authenticator
2016-07-14 16:03:50:622 Wikipedia Debug[main] -[BITHockeyManager(WMFExtensions) wmf_setupAndStart]#L60 I: Starting crash manager.
2016-07-14 16:03:50:622 Wikipedia Debug[main] +[PiwikTracker(WMFExtensions) wmf_start]#L14 E: Not starting Piwik becuase no URL or app ID was found
2016-07-14 16:03:50.758 Wikipedia Debug[14456:1681033] file:///Users/montehurd/Library/Developer/CoreSimulator/Devices/EAA9BD00-3C57-4B66-8C69-3EC123BF48C0/data/Containers/Data/Application/C3D95AC6-66C0-4C39-BBE4-2504CC18C8E5/Documents/
2016-07-14 16:03:50.778 Wikipedia Debug[14456:1681033] [HockeySDK] -[BITHockeyManager invokeStartUpdateManager]/596 INFO: Start UpdateManager
2016-07-14 16:03:50.984 Wikipedia Debug[14456:1681033] -[MWKTitle listIndex]: unrecognized selector sent to instance 0x7fc2ab43aac0
2016-07-14 16:03:50:979 Wikipedia Debug[main] -[WMFLocationManager startMonitoringLocation]#L135 I: <<WMFLocationManager: 0x7fc2ab474330> manager: <CLLocationManager: 0x7fc2ab433c90> delegate: <WMFExploreSectionSchema: 0x7fc2ab453610> is updating: 1> starting monitoring location & heading updates.
2016-07-14 16:03:51.009 Wikipedia Debug[14456:1681033] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MWKTitle listIndex]: unrecognized selector sent to instance 0x7fc2ab43aac0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e79ec65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010e437bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010e7a60ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010e6fc13c ___forwarding___ + 988
	4   CoreFoundation                      0x000000010e6fbcd8 _CF_forwarding_prep_0 + 120
	5   Wikipedia Debug                     0x000000010a4261c9 __29-[MWKList entryForListIndex:]_block_invoke + 73
	6   Wikipedia Debug                     0x000000010a66a499 __31-[NSArray(BlocksKit) bk_match:]_block_invoke + 105
	7   CoreFoundation                      0x000000010e7162a4 __NSArrayGetIndexPassingTest + 612
	8   Wikipedia Debug                     0x000000010a66a39b -[NSArray(BlocksKit) bk_match:] + 459
	9   Wikipedia Debug                     0x000000010a426127 -[MWKList entryForListIndex:] + 199
	10  Wikipedia Debug                     0x000000010a426310 -[MWKList containsEntryForListIndex:] + 80
	11  Wikipedia Debug                     0x000000010a4fe416 -[WMFRelatedSectionBlackList containsEntryForListIndex:] + 134
	12  Wikipedia Debug                     0x000000010a4fe366 -[WMFRelatedSectionBlackList articleURLIsBlackListed:] + 86
	13  Wikipedia Debug                     0x000000010a586797 __97-[WMFExploreSectionSchema sectionsFromHistoryEntriesExcludingExistingTitlesInSections:maxLength:]_block_invoke_2 + 151
	14  Wikipedia Debug                     0x000000010a66aac0 __32-[NSArray(BlocksKit) bk_reject:]_block_invoke + 80
	15  Wikipedia Debug                     0x000000010a66a7d9 __32-[NSArray(BlocksKit) bk_select:]_block_invoke + 105
	16  CoreFoundation                      0x000000010e6d5d2c __NSArrayGetIndexesPassingTest + 620
	17  Wikipedia Debug                     0x000000010a66a6de -[NSArray(BlocksKit) bk_select:] + 446
	18  Wikipedia Debug                     0x000000010a66aa17 -[NSArray(BlocksKit) bk_reject:] + 439
	19  Wikipedia Debug                     0x000000010a58645d -[WMFExploreSectionSchema sectionsFromHistoryEntriesExcludingExistingTitlesInSections:maxLength:] + 541
	20  Wikipedia Debug                     0x000000010a585c60 -[WMFExploreSectionSchema historyAndSavedPageSections] + 160
	21  Wikipedia Debug                     0x000000010a580a93 -[WMFExploreSectionSchema update:] + 963
	22  Wikipedia Debug                     0x000000010a57fad3 +[WMFExploreSectionSchema schemaWithDomainURL:savedPages:history:blackList:locationManager:file:] + 2323
	23  Wikipedia Debug                     0x000000010a57f123 +[WMFExploreSectionSchema schemaWithDomainURL:savedPages:history:blackList:] + 371
	24  Wikipedia Debug                     0x000000010a55838f -[WMFExploreViewController createSectionSchemaIfNeeded] + 511
	25  Wikipedia Debug                     0x000000010a552e17 -[WMFExploreViewController viewDidAppear:] + 1303
	26  UIKit                               0x000000010ce59fb1 -[UIViewController _setViewAppearState:isAnimating:] + 567
	27  UIKit                               0x000000010ce81f79 -[UINavigationController viewDidAppear:] + 173
	28  UIKit                               0x000000010ce59fb1 -[UIViewController _setViewAppearState:isAnimating:] + 567
	29  UIKit                               0x000000010ce94ee6 -[UITabBarController viewDidAppear:] + 108
	30  UIKit                               0x000000010ce59fb1 -[UIViewController _setViewAppearState:isAnimating:] + 567
	31  CoreFoundation                      0x000000010e6e8026 __53-[__NSArrayI enumerateObjectsWithOptions:usingBlock:]_block_invoke + 70
	32  CoreFoundation                      0x000000010e6e7f5c -[__NSArrayI enumerateObjectsWithOptions:usingBlock:] + 284
	33  UIKit                               0x000000010ce5a109 -[UIViewController _setViewAppearState:isAnimating:] + 911
	34  UIKit                               0x000000010ce5aafb -[UIViewController _executeAfterAppearanceBlock] + 52
	35  UIKit                               0x000000010cd495ec _applyBlockToCFArrayCopiedToStack + 314
	36  UIKit                               0x000000010cd49485 _afterCACommitHandler + 564
	37  CoreFoundation                      0x000000010e6d1ca7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	38  CoreFoundation                      0x000000010e6d1c00 __CFRunLoopDoObservers + 368
	39  CoreFoundation                      0x000000010e6c7a33 __CFRunLoopRun + 1123
	40  CoreFoundation                      0x000000010e6c7366 CFRunLoopRunSpecific + 470
	41  GraphicsServices                    0x0000000111913a3e GSEventRunModal + 161
	42  UIKit                               0x000000010cd258c0 UIApplicationMain + 1282
	43  Wikipedia Debug                     0x000000010a51a75a main + 186
	44  libdyld.dylib                       0x000000010fb5a145 start + 1
	45  ???                                 0x0000000000000007 0x0 + 7
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
</pre>

**Comment by coreyfloyd** [comment]
@montehurd @joewalsh this pr is ready to be reviewed.

(I still have 2 check boxes to check but one is just about renaming some methods and the other is about filing a ticket)

**Comment by montehurd** [comment]
@coreyfloyd found a couple bugs

Editing:
- load an article
- tap edit icon and you get an "unable to obtain latest revision" error message (guessing the query parameters for retrieving wikitext needs attention)

Search language switching:
- crashes when i try to switch from English to another search lang

**Comment by montehurd** [comment]
One more bug:

- add "test" as a search lang
- switch to "test" as a search lang and search for "bird"
- results are still results from "English"

**Comment by montehurd** [comment]
Confirmed the issue above with Arabic as well.

**Comment by montehurd** [comment]
crash on tap on link w fragment:

a mov

**Comment by montehurd** [comment]
@coreyfloyd 

quick reminder: tapping the following 2 links is broken in production and iirc there is a ticket for this issue. since you're knee deep in the url code maybe you can knock it out?

screen shot 2016-07-18 at 2 36 20 pm

Note that all of these links work fine if you load the test wiki bird article in safari, so the link format is correct and the articles all exist.

**Comment by coreyfloyd** [comment]
@montehurd need to use the solution that @joewalsh had before - passing the article URL explicitly to the web view controller so it can scroll to the proper section. 

We should change this - passing both the article URL and article feels dirty… but the URL on the article is the real-non-fragment version… which makes sense - its how it should be.

**Comment by montehurd** [comment]
The link circled below doesn't work if you tap it on production or 5.0.5, but it *does* work with this PR :)
screen shot 2016-07-18 at 3 43 05 pm

**Comment by coreyfloyd** [comment]
@montehurd there isn't really anything to add to the tests. The web controller was literally just ignoring the URL for the Spanish page and making a new URL based on the current article language. Developer error.

**Comment by coreyfloyd** [comment]
@joewalsh @montehurd can you guys give this another once over? Should be good to go. Its all caught up with develop

**Comment by coreyfloyd** [comment]
Note: 
Needed to do some further fixing of unit test configurations because of the was that testing works in swift.

**Comment by joewalsh** [comment]
Did a quick once over of the code changes and nothing major jumped out at me. Checked the functionality of image galleries, articles, and the history list.

**Comment by joewalsh** [comment]
one request - could you eliminate the warnings before merging?

**Comment by coreyfloyd** [comment]
@joewalsh I don't want to do a release with those warnings but I did want to leave them in until I address those (will do in my next PR). 

I just don't want extra methods hanging around when we don't need them - its a bit confusing to have so many ways to make a URL, but I want to get this merged while its good.

Is that ok?

**Comment by joewalsh** [comment]
@coreyfloyd I understand that it will be fixed before release, but my concern was having compiler warnings on develop that make it harder to discern when new warnings are added. I made some commits that fixed the easier warnings and changed the others to WMF_TECH_DEBT_TODO. Let me know if this works for you

**Comment by coreyfloyd** [comment]
@joewalsh done

**Comment by joewalsh** [comment]
:+1:

**Comment by coreyfloyd** [comment]
Uhh… why is this failing now… ugh

**Pull request merged**
