### PR TITLE
Adding Piwik event tracking

### PR DESCRIPTION
**Pull request by coreyfloyd**
This adds the pod and then sets up tracking for the tabs, article page views and preview interactions (follow through or dismiss)

This is what the dashboard looks like for tracking events:

screenshot 2015-08-12 18 27 51

### CODE REVIEW

**Comment by bgerstle** [comment]
wow time on page, nice!!

**Comment by bgerstle** [comment]
:-1: just a few minor comments, let me know what you think

**Comment by coreyfloyd** [comment]
New screen cap

screenshot 2015-08-13 09 51 56

**Comment by bgerstle** [comment]
:+1: just one minor comment about the casting of `self.article` in `WMFArticleViewController`.

**Comment by coreyfloyd** [comment]
@bgerstle updated to address the casting and merged in master

**Comment by bgerstle** [comment]
@coreyfloyd cool, will wait for travis then act accordingly :+1:

**Pull request merged**
