### PR TITLE
[Talk Pages Dev] Support list items in html-to-attributed string code

### PR DESCRIPTION
**Pull request by nambatee**
https://phabricator.wikimedia.org/T222760

Known endpoint bugs:

1. List is closed prematurely if it includes a nested list

User talk HTML:

```
<ul>
  <li>Unordered list item one 🐸
  <li>Unordered list item two 🐸
  <li>Nested 🐸
    <ol>
      <li>Nested ordered list item one 🐵
      <li>Nested ordered list item two 🐵
    </ol>
</ul>
```

Endpoint response (added new lines + indentation for clarity):

```
<ul>
  <li>Unordered list item one 🐸
  <li>Unordered list item two 🐸
  <li>Nested 🐸
</ul> // ul closed prematurely
<ol>
  <li>Nested ordered list item one 🐵
  <li>Nested ordered list item two 🐵
</ol>
```

Test: https://en.wikipedia.org/wiki/User_talk:Badylek#Nested_tags_test_1

2. Lost `li` tags

User talk HTML:

```
<ol>
  <li>Ordered list item one 🍓
  <li>Nested 🍓
    <ul>
      <li>Nested <i>unordered <b>list</b> item</i> one 🎲
      <li>Nested unordered list item two 🎲
    </ul>
  <li>Ordered list item three ☠️
</ol>
```

Endpoint response (added new lines + indentation for clarity):

```
<ol>
  <li>Ordered list item one 🍓
  <li>Nested 🍓
</ol> // ol closed prematurely
<ul>
  <li>Nested <i>unordered <b>list</b> item</i> one 🎲
  <li>Nested unordered list item two 🎲
</ul>
Ordered list item three ☠️ // fell out of list cause it was closed, missing li tag
</ol>
```

Test: https://en.wikipedia.org/wiki/User_talk:Badylek#Nested_tags_test_2

---

This is what's rendered with the current response and the corrected response for https://en.wikipedia.org/wiki/User_talk:Badylek#Nested_tags_test_1:

short list

This is what's rendered with the current response and the corrected response for https://en.wikipedia.org/wiki/User_talk:Badylek#Test (longer html with many lists):

many lists

### CODE REVIEW

**Comment by montehurd** [comment]
seems to be missing the list items:

Screen Shot 2019-05-30 at 1 57 58 PM

**Comment by montehurd** [comment]
@tonisevener pointed out that i'm not seeing anything beneath the first parts 'cause we're truncating the intro, which is probably fine - updating my talk page to have another section so i can proof list item parsing aside from the truncation 😜

**Comment by montehurd** [comment]
The first topic on my test wiki user page looks ok...
Screen Shot 2019-05-30 at 2 45 49 PM

... but the second one has some issues:
Screen Shot 2019-05-30 at 2 50 29 PM

Left is app, middle is https://test.wikipedia.org/api/rest_v1/page/html/User_talk%3Amontehurd and right side is output of (handy for visualizing endpoint output):

```
<html>
<script>
// fetch('http://localhost:6927/en.wikipedia.org/v1/page/talk/User_talk:Brion_VIBBER/895522398').then(response => {
// fetch('http://localhost:6927/en.wikipedia.org/v1/page/talk/User_talk:Montehurd/899425787').then(response => {
fetch('https://talk-pages.wmflabs.org/en.wikipedia.org/v1/page/talk/User_talk:montehurd').then(response => {
  response.json().then(json => {
	  json.topics.forEach(topic => {
      const topicDiv = document.createElement('div')
      topicDiv.style.margin = '20px 0px 20px 0px'
      topicDiv.style.padding = '5px'
      topicDiv.style.border = '1px dashed blue'
      topicDiv.style.marginLeft = `${30 * (topic.depth - 1)}px`

      const h = document.createElement(`h${topic.depth}`)
      h.innerHTML = `${topic.text} [${topic.id}]`
      topicDiv.appendChild(h)

      topic.replies.forEach(item => {
        const d = document.createElement('div')
        d.style.border = '1px solid red'
        d.style.marginLeft = `${25 * item.depth}px`
        d.style.marginBottom = '5px'
        d.style.padding = '5px'
        d.innerHTML = item.text
        topicDiv.appendChild(d)
      })

      document.body.appendChild(topicDiv)
    })
  })
})
</script>
<body>
</body>
</html>

```

**Comment by montehurd** [comment]
As Josh pointed out, looks like the “missing monkey” bug may be an off-by-one issue, which may be cascading down causing the issues in the second screenshot.

**Comment by nambatee** [comment]
Thanks for testing @montehurd - it looks like the double lists aren't being handled properly. I'll take a look at it when I'm back.

**Comment by joewalsh** [comment]
Simulator Screen Shot - iPhone X - 2019-05-31 at 08 08 40
The first issue is happening on the main branch as well, so is separate from list handling. If the double nested setup isn't very common (and/or Josh OKs it as not needing to be handled initially) the second issue could be handled as a follow-on.

**Pull request merged**
