### PR TITLE
Fix Potd crash

### PR DESCRIPTION
**Pull request by coreyfloyd**
inserting nil - doh!

https://phabricator.wikimedia.org/T128554

### CODE REVIEW

**Comment by montehurd** [comment]
SHIPIT!

**Comment by bgerstle** [comment]
@coreyfloyd won't this cause the feed to contain empty sections in this case? it might be better to catch this in the response serializer/fetcher and treat as an error so we can display the proper empty/error view in the feed and retry at the appropriate time.

**Comment by bgerstle** [comment]
also not seeing this crash on master, maybe resolved on the back-end somehow?

**Comment by bgerstle** [comment]
are you _sure_ the response was `nil`? i just ran into a case where the section itself was `nil` (in this case , was main page because it had been deallocated)

**Comment by coreyfloyd** [comment]
@bgerstle the crash log says it is nil. 

Regardless, we shouldn't be putting a possible nil value into an array without checking it.

As far as treating it as an error - yeah we can do that…

**Comment by bgerstle** [comment]
:+1:

**Pull request merged**
