### PR TITLE
Spotlight fix - Stop using display title!!!

### PR DESCRIPTION
**Pull request by coreyfloyd**
oh html…

### CODE REVIEW

**Comment by montehurd** [comment]
:+1:

**Comment by montehurd** [comment]
Hmm...
screen shot 2016-03-02 at 10 54 44 am

**Comment by bgerstle** [comment]
@montehurd maybe an old index record? @coreyfloyd is there a way to reset that?

**Comment by coreyfloyd** [comment]
@montehurd yeah - thats old. Probably if you delete the app it will delete the index (i don't know for sure)

**Comment by montehurd** [comment]
Just deleted it... same thing...

**Comment by montehurd** [comment]
The icon says 565... huh...

**Comment by coreyfloyd** [comment]
@montehurd actually i only did nsuseractivity… updating the spotlight one now - good catch

**Comment by bgerstle** [comment]
> The icon says 565... huh...

@montehurd this is expected for dev builds. we only bump the build number on the jenkins machine before deploying

**Comment by bgerstle** [comment]
HTML is gone, but new issue discovered (titles aren't being de-duped between activities & saved pages).

**Comment by bgerstle** [comment]
so, :+1: on this, but might need a separate PR for other issue

**Comment by bgerstle** [comment]
:+1: looks good now, but still showing app icon even though article has lead image. i'll file an issue for that

**Pull request merged**
