### PR TITLE
Make sure language buttons stay left aligned

### PR DESCRIPTION
**Pull request by coreyfloyd**

### CODE REVIEW

**Comment by bgerstle** [comment]
:+1:

**Comment by bgerstle** [comment]
@montehurd can you double check this?

**Comment by montehurd** [comment]
Seeing ellipses issue...
untitled mov

**Comment by montehurd** [comment]
Still seeing it. Repro steps:

untitled mov

**Comment by coreyfloyd** [comment]
screenshot 2016-03-02 15 10 05


@montehurd Not sure why you are still seeing it - I am not. Regardless, at this point you can file a ticket if its still an issue. Shouldn't be a blocker. Especially since it isn't all the time.

**Comment by montehurd** [comment]
@coreyfloyd can you try the exact repro steps in my gif? (Same langs in same order) Curious if it's just my simulator.

**Comment by coreyfloyd** [comment]
@montehurd yeah I did - not sure why its being fussy with you. I also tried clicking about 30 other ones and never get that issue anymore. 

It was pretty clear why you saw the issue before I made the fix… but I am at a loss at why you would see it now. You might want to clear out some stuff or try other devices. But otherwise like I said we should file a ticket for 5.0.1.

**Comment by montehurd** [comment]
:+1: ya further tweaks can be follow-ons.

**Pull request merged**
