### PR TITLE
Fix content offset at about screen

### PR DESCRIPTION
**Pull request by akarataev**
https://phabricator.wikimedia.org/T229528

## Screenshots
Artboard

### CODE REVIEW

**Comment by montehurd** [comment]
Any time to double-check the possible fix I mentioned? 🤔

**Comment by tonisevener** [comment]
@akarataev also just a heads up - our develop branch has been updated for Xcode 11 beta 7, in case you start seeing build errors

**Comment by akarataev** [comment]
@montehurd hello,

thanks for the hint, I'll check it such possible as soon.

**Comment by akarataev** [comment]
Hello @montehurd, @tonisevener 
 
I've updated the branch. New solution is based on `iOS12yOffsetHack` and JavaScript.
I couldn’t make a result with `top` fragment, because it also has an incorrect offset.

**Comment by montehurd** [comment]
> [wv loadHTMLFromAssetsFile:kWMFAboutHTMLFile scrolledToFragment:@"#top"];

^ this change to L134 seems to work on my end... though I haven't tested all scenarios🤞. Is it give you an incorrect offset?

**Comment by akarataev** [comment]
Oh, you right, it works fine. It strange because `<a href="#top">` under WebView works incorrect.
Thanks for good point and patience. I've updated branch.

**Pull request merged**
