### PR TITLE
Fix gallery crash on iOS 8 RTL

### PR DESCRIPTION
**Pull request by bgerstle**
Phab: 
- bug fix [T120863](https://phabricator.wikimedia.org/T120863) 
- increase visual test coverage across OS versions [T120773](https://phabricator.wikimedia.org/T120773)
- run tests on iOS 8 in parallel via travis build matrix [T120771](https://phabricator.wikimedia.org/T120771)

We weren't setting the data source on the collection view before applying the current page, which resulted in a crash.

Now for the fun stuff:

- get all tests passing on iOS 8 :white_check_mark: 
- make visual tests device agnostic (iOS 8 & 9, for different system fonts and other things) 📸
- add iOS 8 to Travis build matrix 👷🤖

### CODE REVIEW

**Comment by coreyfloyd** [comment]
:+1:

**Comment by coreyfloyd** [comment]
well I guess as soon as it builds i am good…

**Comment by bgerstle** [comment]
@coreyfloyd trying a bit more to make it build after a break, if it fails we can run "the matrix" on Jenkins serially. i am able to consistently reproduce an EXC_BAD_ACCESS from `WMFArticleFetcherTests` when it times out. Not sure if it's the issue we're seeing here, but worth trying.

**Comment by coreyfloyd** [comment]
ok - let me know if you need any help

**Comment by bgerstle** [comment]
there's only one person who can help me now :pray: but yeah, would really appreciate it if you had a look. there's not much to go on, unfortunately :disappointed:. I could try again w/ using "raw" `xcodebuild` output (since we silence warnings now) and we might not hit the 4MB log limit. That might tell us something, but maybe not.

**Comment by bgerstle** [comment]
i've never been able to repro the "no build output" issue seen on Travis

**Comment by montehurd** [comment]
:+1: Waiting on Mr. Travis...

**Pull request merged**
