### PR TITLE
Clean up tab bar

### PR DESCRIPTION
**Pull request by coreyfloyd**
Based on #26. Please review that first.

Added icons and embedded each tab contents in a navigation controller. 

Needed to embed the navigation controller for https://phabricator.wikimedia.org/T106113 so figured do this with the tab icons.

### CODE REVIEW

**Comment by bgerstle** [comment]
@coreyfloyd y u no screenshot? 😥

**Comment by coreyfloyd** [comment]
For brian:

screenshot 2015-08-03 15 45 08

**Comment by coreyfloyd** [comment]
err @bgerstle

**Comment by bgerstle** [comment]
LGTM, but a bookmark instead of a heart? is that from design?

**Comment by bgerstle** [comment]
anyway, :+1:

**Comment by montehurd** [comment]
:-1: 
 
Nearby constraints are way broken. Rotate to landscape and back to portrait to repro.

**Comment by montehurd** [comment]
:+1: 
Opps nevermind! This issue pre-dates your patch and it looks to be an issue with whatever is containing nearby, not nearby itself.

**Pull request merged**
