### PR TITLE
Add deletion to saved pages

### PR DESCRIPTION
**Pull request by coreyfloyd**
Adding delete support to the article list collection view
- Subclassed the set sizing layout
- Implemented the delegate methods to support deletion

Mostly this was moving the logic from the TGLStacklayout into a subclass.

### CODE REVIEW

**Comment by bgerstle** [comment]
@coreyfloyd can you merge or rebase master? I can't really test since it has the article loading issue. However, the app [crashed](https://gist.github.com/bgerstle/aeabd16dffc0dacfe9bf) when I deleted an article from recent by swiping.

**Comment by bgerstle** [comment]
Swiping to delete on saved seems to work OK though

**Comment by coreyfloyd** [comment]
@bgerstle updated - working now for me… go ahead and check to let me know if you are good.

**Comment by bgerstle** [comment]
:+1: :shipit:

**Pull request merged**
