### PR TITLE
don't allow the interactive pop gesture recognizer to start if there's only 1 view controller on the stack

### PR DESCRIPTION
**Pull request by joewalsh**

### CODE REVIEW

**Comment by montehurd** [comment]
@joewalsh hey I'm seeing something weird on the welcome VC with edge drag... (maybe unrelated to this PR?)

welcome mov

**Comment by montehurd** [comment]
@joewalsh batcave? irc cloud is down :(

**Comment by joewalsh** [comment]
What are the repro steps? I’m not seeing it

**Comment by montehurd** [comment]
@joewalsh I'm seeing it about 50% of the time - most often when tapping through to the last welcome panel, then dragging from left edge to go back to the first panel.

**Comment by montehurd** [comment]
+1 (the issue from the animated gif above looks to be unrelated)

**Pull request merged**
