### PR TITLE
Include CSS styles from syntax highlighting module.

### PR DESCRIPTION
**Pull request by dbrant**
This pulls in CSS styles from the `ext.pygments` module, which contains styles for syntax highlighting in articles where code blocks are written using the `<syntaxhighlight>` tag.  I regenerated the CSS files by running `make web`, which also indirectly updated `package_lock.json`... Let me know if this is not correct.
https://phabricator.wikimedia.org/T180332

### CODE REVIEW

**Comment by montehurd** [comment]
Tested on `enwiki > Lua (programming language) > Syntax`

ltgm

# Before:
screen shot 2017-11-17 at 11 52 13 am


# After:
screen shot 2017-11-17 at 11 51 31 am

**Comment by montehurd** [comment]
@nambatee @joewalsh Looks like we should have been including this all along...

**Comment by nambatee** [comment]
👍

**Comment by montehurd** [comment]
retest this please

**Comment by montehurd** [comment]
Related: one-line pagelib fix for code highlighting theme-ing:
https://github.com/wikimedia/wikimedia-page-library/pull/102

**Pull request merged**
