### PR TITLE
Code/running static analyzer

### PR DESCRIPTION
**Pull request by barbaramartina**
Changes after running static analyzer on the project: some memory leaks fix + some TODOs.

The first two commits are commented so these lines can be checked by people with more knowledge about the project code:
1. [8ff1d20](https://github.com/wikimedia/wikipedia-ios/commit/8ff1d206a01fd75e95d57326f660d974193d1326) 
2.  [4af530b](https://github.com/wikimedia/wikipedia-ios/commit/4af530bbdcd55b061213adec57fc829d4ee5e990) 

I also run [FUI](https://github.com/dblock/fui) and detected the following classes are not being used, but preferred not to delete any for the moment:

* Wikipedia/Code/AlertLabel.h
* Wikipedia/Code/DDLog+WMFLogger.h
* Wikipedia/Code/MWKSectionMetaData.h
* Wikipedia/Code/NSAttributedString+WMFSavedPagesAttributedStrings.h
* Wikipedia/Code/ShareMenuSavePageActivity.h
* Wikipedia/Code/ThumbnailFetcher.h
* Wikipedia/Code/TopActionSheetLabel.h
* Wikipedia/Code/UIView+WMFShadow.h
* Wikipedia/Code/WMFArticleProtocol.h
* Wikipedia/Code/WMFBorderButton.h
* Wikipedia/Code/WMFBundledImageProtocol.h
* Wikipedia/Code/WMFHamburgerMenuFunnel.h
* Wikipedia/Code/WMFLocalizationProtocol.h
* Wikipedia/Code/WMFSearchFunnel.h
* Wikipedia/Code/WMFSuggestedPagesFunnel.h
* Wikipedia/Code/Wikipedia-Bridging-Header.h
* WikipediaUnitTests/Code/MWKListInsertionTests.h
* WikipediaUnitTests/Code/SavedArticlesFetcherTests.h
* WikipediaUnitTests/Code/WMFCodingStyle.h
* WikipediaUnitTests/Code/WikipediaUnitTests-Bridging-Header.h

### CODE REVIEW

**Comment by bgerstle** [comment]
@barbaramartina thanks for the list of unused classes! some of those are in use, even though they might not be imported anywhere (e.g. WMFLogging uses `load` to customize CocoaLumberjack, and doesn't need to be imported anywhere).  we can use that tool in the future to remove dead code on a semi-regular basis.

**Comment by barbaramartina** [comment]
@bgerstle no problem, I preferred not to delete exactly for that reasons, just in case they were used somehow. The FUI tool was very useful.

**Comment by bgerstle** [comment]
@barbaramartina are you still planning to amend this PR? if so, please mention one of us when it's ready for re-review.

**Comment by barbaramartina** [comment]
Hi Brian, yes it's my next thing to do, but I have not been in my house these days... I was planning to do it tomorrow. I will mention one of u.

**Comment by bgerstle** [comment]
@barbaramartina great :grinning:

**Comment by barbaramartina** [comment]
@bgerstle  PR is ready to review again thanks!

**Comment by bgerstle** [comment]
@barbaramartina i can't tell where the conflict was in `1ac3d4e` but i assume it was insignificant

**Comment by bgerstle** [comment]
:+1: @coreyfloyd or @montehurd please review/merge

**Pull request merged**
